import { PresetDefinition } from '../types';

export const AFFILIATE_PRESETS: PresetDefinition[] = [
  {
    code: '/shopee-clean-demo',
    label: 'Shopee Clean Demo',
    category: 'affiliate_marketplace',
    description: 'Demonstração limpa de produto com fundo branco para Shopee e marketplaces.',
    bestFor: ['Demonstrações de produto', 'Vídeos sem diálogo', 'Achadinhos Shopee', 'Anúncios UGC de conversão'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator', 'copy_master'],
    outputModes: ['storyboard', 'campaign', 'single_prompt', 'video_sequence'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Shopee',
    visualDNA: [
      'Clean pure white seamless background',
      'Centered product placement with realistic scale',
      'Hand-held natural product demonstration',
      'High-key crisp studio lighting with soft natural shadows',
      'Dedicated negative space for on-screen TikTok/Shopee cart overlay'
    ],
    commercialDNA: [
      'Hook: Immediate benefit proof in first 2 seconds',
      'Body: Multi-angle tactile test and ergonomic showcase',
      'CTA: Direct push to Shopee bag/cart icon'
    ],
    defaultTakes: 5,
    promptAdditions: [
      'Create a clean Shopee-style product demonstration with a pure white background, crisp high-key lighting, centered product framing, tactile hand-held demonstration, clear ergonomic proof, and designated negative space for on-screen cart CTA text.'
    ],
    negativePromptAdditions: [
      'cluttered background, dark shadows, noisy environment, distorted hands, extra fingers, blurry product label, illegible logos'
    ],
    ctaSuggestions: ['Tá na Shopee 🧡', 'Veja na sacolinha', 'Confira no carrinho laranja', 'Link no perfil'],
    tags: ['shopee', 'afiliado', 'fundo-branco', 'demo', 'clean', 'conversao'],
    suggestedCampaignType: 'shopee_clean_demo',
    suggestedSceneStyle: 'white_background',
    suggestedFormat: 'no_dialogue',
    suggestedPlatform: 'shopee'
  },
  {
    code: '/tiktokshop-fast-demo',
    label: 'TikTok Shop Fast Demo',
    category: 'affiliate_marketplace',
    description: 'Demonstração rápida e dinâmica com ganchos visuais para TikTok Shop.',
    bestFor: ['TikTok Shop', 'Reels rápidos', 'Ganchos visuais nos 3 primeiros segundos', 'Demonstração dinâmica'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt', 'video_sequence'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'TikTok Shop',
    visualDNA: [
      'Vertical 9:16 high-energy framing',
      'Dynamic hand movements revealing key features',
      'Bright modern ring-light illumination',
      'Fast visual transitions and snap zooms',
      'High color contrast and modern lifestyle setting'
    ],
    defaultTakes: 5,
    promptAdditions: [
      'Generate a fast-paced vertical 9:16 TikTok Shop conversion creative with dynamic hand demonstrations, high color saturation, crisp modern lighting, clear product focus, and snap visual engagement.'
    ],
    negativePromptAdditions: ['slow boring pacing, dull colors, low contrast, washed out lighting, blurry details'],
    ctaSuggestions: ['Clica na sacolinha aqui embaixo 👇', 'Garanta com frete grátis', 'Tá no precinho hoje!'],
    tags: ['tiktok', 'tiktok-shop', 'rapido', 'dinamico', 'afiliado', 'viral'],
    suggestedCampaignType: 'tiktok_fast_demo',
    suggestedSceneStyle: 'lifestyle_clean',
    suggestedFormat: 'fast_pacing',
    suggestedPlatform: 'tiktok_shop'
  },
  {
    code: '/amazon-affiliate',
    label: 'Amazon Affiliate Showcase',
    category: 'affiliate_marketplace',
    description: 'Apresentação refinada e confiável para afiliados Amazon e Storefront.',
    bestFor: ['Achadinhos Amazon', 'Vídeos de unboxing', 'Review prático de utilidades', 'Pinterest pins'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Amazon',
    visualDNA: [
      'Neutral aesthetic home or clean countertop setting',
      'Premium soft diffusion lighting',
      'Clear unboxing and immediate practical usage',
      'Organized and aspirational lifestyle staging'
    ],
    defaultTakes: 5,
    promptAdditions: [
      'Create an Amazon-style aesthetic product showcase set in a clean minimalist modern home, highlighting authentic practical utility, clean soft daylight, and premium build quality.'
    ],
    negativePromptAdditions: ['messy room, chaotic props, plastic glare, cheap look, overexposed lighting'],
    ctaSuggestions: ['Link na bio / Storefront', 'Achadinho indispensável da Amazon', 'Comenta QUERO que te envio o link'],
    tags: ['amazon', 'amazon-finds', 'achadinho', 'afiliado', 'storefront'],
    suggestedPlatform: 'amazon'
  },
  {
    code: '/amazon-pinterest-pin',
    label: 'Amazon Pinterest Pin',
    category: 'affiliate_marketplace',
    description: 'Pin vertical 2:3 estético e altamente salvável para afiliados Amazon e Pinterest.',
    bestFor: ['Pinterest Shoppable Pins', 'Amazon Associates', 'Descoberta visual', 'Tráfego orgânico'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Pinterest',
    visualDNA: [
      'Vertical 2:3 aspect ratio composition',
      'Aspirational warm neutral decor and soft aesthetic',
      'Hero product staging with intentional typography space',
      'Warm sunlight bokeh and elegant texture display'
    ],
    promptAdditions: [
      'Create a vertical Pinterest-ready Amazon affiliate product Pin with a clean aspirational composition, clear product visibility, soft lifestyle styling, warm natural sunlight, and space for elegant text overlay.'
    ],
    negativePromptAdditions: ['cluttered frame, harsh shadows, aggressive sales banners, low resolution, cheap filters'],
    ctaSuggestions: ['Veja na Amazon', 'Amazon Find indispensável', 'Salve esse achadinho no seu board 📌'],
    tags: ['pinterest', 'amazon', 'pin', 'vertical', 'salvavel', 'estetico']
  },
  {
    code: '/pinterest-product-pin',
    label: 'Pinterest Product Pin',
    category: 'affiliate_marketplace',
    description: 'Formato editorial 2:3 voltado para curadoria visual e cliques de compra.',
    bestFor: ['Pins de moda e decoração', 'Achados de estilo', 'Curadoria de produtos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Pinterest',
    visualDNA: ['Vertical 2:3 ratio', 'Editorial soft tones', 'Curated aesthetic props', 'Clean negative space'],
    promptAdditions: ['Vertical 2:3 aesthetic Pinterest pin photography, curated styling, soft airy lighting, clean elegance.'],
    negativePromptAdditions: ['loud neon colors, ugly borders, intrusive text, low contrast'],
    ctaSuggestions: ['Inspiração do dia', 'Clique para ver onde comprar', 'Salve na sua pasta'],
    tags: ['pinterest', 'curadoria', 'estilo', 'pin']
  },
  {
    code: '/mercadolivre-clean-demo',
    label: 'Mercado Livre Clean Demo',
    category: 'affiliate_marketplace',
    description: 'Demonstração de produto focada em confiança, envio rápido e detalhes de fabricação.',
    bestFor: ['Mercado Livre Shorts', 'Clipes de produto', 'Demonstração de durabilidade'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Mercado Livre',
    visualDNA: ['Clean commercial lighting', 'High fidelity product finish', 'Clear scale reference with human hands'],
    promptAdditions: ['Commercial product video frame with high clarity, clean white/gray neutral setup, honest build inspection.'],
    negativePromptAdditions: ['fictional props, distorted brand markings, fake textures'],
    ctaSuggestions: ['Compre com envio Full ⚡', 'Disponível no Mercado Livre', 'Pronta entrega com garantia'],
    tags: ['mercadolivre', 'full', 'confianca', 'afiliado'],
    suggestedPlatform: 'mercado_livre'
  },
  {
    code: '/magalu-achadinhos',
    label: 'Magalu Achadinhos',
    category: 'affiliate_marketplace',
    description: 'Estilo acolhedor e dinâmico para ofertas e achadinhos do Magazine Luiza.',
    bestFor: ['Parceiro Magalu', 'Achadinhos de casa e cozinha', 'Promoções relâmpago'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Magalu',
    visualDNA: ['Warm family home setting', 'Bright accessible lighting', 'Clear practical problem solving'],
    promptAdditions: ['Warm Brazilian home lifestyle product clip, inviting natural daylight, relatable and clear demonstration.'],
    negativePromptAdditions: ['cold dark studio, luxury untouchable vibe, artificial blur'],
    ctaSuggestions: ['Tem no Magalu!', 'Corre que tá na promoção', 'Link seguro nos Stories'],
    tags: ['magalu', 'achadinho', 'casa', 'afiliado']
  },
  {
    code: '/aliexpress-finds',
    label: 'AliExpress Finds & Gadgets',
    category: 'affiliate_marketplace',
    description: 'Foco em gadgets inovadores, unboxing satisfatório e curiosidade visual.',
    bestFor: ['Gadgets tecnológicos', 'Ferramentas práticas', 'Testes de durabilidade'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'AliExpress',
    visualDNA: ['High-contrast tech lighting', 'Macro closeup of mechanisms', 'Fast satisfying reveal'],
    promptAdditions: ['Futuristic gadget demo, crisp tabletop setup, high contrast detail shots showing moving parts and functionality.'],
    negativePromptAdditions: ['dusty surface, scratches, out of focus camera'],
    ctaSuggestions: ['Inovação por menos de R$50', 'Achado imperdível', 'Link na descrição'],
    tags: ['aliexpress', 'gadget', 'tecnologia', 'inovacao']
  },
  {
    code: '/shein-finds',
    label: 'SHEIN Finds & Haul',
    category: 'affiliate_marketplace',
    description: 'Foco em provador ágil, combinação de looks acessíveis e tendências de moda.',
    bestFor: ['Hauls de moda', 'Acessórios em alta', 'Estilo jovem e trendy'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'SHEIN',
    visualDNA: ['Modern aesthetic bedroom or mirror setup', 'Trendy warm lighting', 'Full outfit framing with close-ups'],
    promptAdditions: ['Trendy fashion haul video frame, natural ring light, modern youth bedroom aesthetic, stylish fit demonstration.'],
    negativePromptAdditions: ['wrinkled fabric artifacts, distorted body anatomy, mismatched patterns'],
    ctaSuggestions: ['ID da peça na legenda', 'Cupom de desconto ativo', 'Nota para esse look de 0 a 10?'],
    tags: ['shein', 'haul', 'look', 'moda', 'tendencia'],
    suggestedCampaignType: 'fashion_carousel'
  },
  {
    code: '/facebook-shopee-ad',
    label: 'Facebook & Instagram Feed Ad',
    category: 'affiliate_marketplace',
    description: 'Criativo de alta retenção com título claro e demonstração direta.',
    bestFor: ['Tráfego pago', 'Anúncios de feed 1:1 e 4:5', 'Conversão direta'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Facebook',
    visualDNA: ['Square 1:1 or 4:5 vertical', 'Eye-catching focal point in center', 'Bright high-stopping-power colors'],
    promptAdditions: ['High CTR commercial ad photo, centered hero product with vibrant complementary background, clean professional look.'],
    negativePromptAdditions: ['dull colors, small unreadable product, chaotic background'],
    ctaSuggestions: ['Comprar Agora', 'Oferta por tempo limitado', 'Saiba Mais no site'],
    tags: ['facebook', 'ads', 'trafego-pago', 'feed']
  },
  {
    code: '/white-glove-packshot',
    label: 'White Glove Packshot',
    category: 'affiliate_marketplace',
    description: 'Demonstração de produto com luvas brancas em fundo infinito para sensação premium.',
    bestFor: ['Joias', 'Eletrônicos finos', 'Cosméticos de luxo', 'Inspeção de qualidade'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Generic',
    visualDNA: [
      'Clean white cloth gloves handling the item',
      'Seamless white acrylic or matte background',
      'Micro-reflection and pinpoint specular highlights',
      'Precise 360-degree rotation presentation'
    ],
    defaultTakes: 5,
    promptAdditions: [
      'High-end white glove product demonstration, seamless pure white background, precision studio lighting, delicate tactile inspection, immaculate reflection and zero dust.'
    ],
    negativePromptAdditions: ['bare hands with flaws, dirty gloves, fingerprints, smudges on product, noisy floor'],
    ctaSuggestions: ['Qualidade premium garantida', 'Detalhes impecáveis', 'Veja de perto'],
    tags: ['luva-branca', 'white-glove', 'packshot', 'luxo', 'inspecao'],
    suggestedCampaignType: 'white_glove_packshot',
    suggestedSceneStyle: 'white_background'
  },
  {
    code: '/hand-demo',
    label: 'Hand-Held Product Demo',
    category: 'affiliate_marketplace',
    description: 'Demonstração em primeira pessoa segurando e interagindo com o produto.',
    bestFor: ['Smartphones', 'Acessórios de beleza', 'Utensílios de mão', 'Amostra de textura'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'campaign', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Generic',
    visualDNA: ['Natural manicured hand holding product', 'Depth of field with soft background', 'Real-world scale perspective'],
    promptAdditions: ['First-person POV hand holding product, natural ergonomic grip, soft cinematic depth of field blur in background.'],
    negativePromptAdditions: ['malformed hands, extra fingers, missing thumbs, unnatural grip'],
    ctaSuggestions: ['Perfeito para o dia a dia', 'Leve e ergonômico', 'Veja como funciona'],
    tags: ['mao', 'hand-held', 'pov', 'interacao', 'escala']
  },
  {
    code: '/conversion-carousel',
    label: 'Conversion Carousel',
    category: 'affiliate_marketplace',
    description: 'Sequência lógica de slides para carrosséis de venda no Instagram e marketplaces.',
    bestFor: ['Carrosséis de 5 cards', 'Passo a passo de benefícios', 'Quebra de objeções'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator', 'copy_master'],
    outputModes: ['carousel', 'storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Instagram',
    visualDNA: ['Consistent brand color palette across cards', 'Progressive visual storytelling', 'Clear title zones on top/bottom'],
    promptAdditions: ['Cohesive multi-slide carousel set, matching lighting, progressive benefit reveal from hook to CTA.'],
    negativePromptAdditions: ['inconsistent color themes between cards, mismatched lighting, chaotic layout'],
    ctaSuggestions: ['Arraste para o lado 👉', 'Qual seu modelo favorito?', 'Salva para não esquecer'],
    tags: ['carrossel', 'slides', 'beneficios', 'conversao']
  },
  {
    code: '/product-in-hand',
    label: 'Product in Hand Macro',
    category: 'affiliate_marketplace',
    description: 'Close focado no produto nas mãos destacando material e acabamento.',
    bestFor: ['Textura de frascos', 'Acessórios e carteiras', 'Detalhes finos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Generic',
    visualDNA: ['Macro lens focus on product surface', 'Soft hand holding gently', 'Subtle reflections on material'],
    promptAdditions: ['Macro shot of product held delicately in hand, razor-sharp focus on texture and embossing, soft ambient lighting.'],
    negativePromptAdditions: ['blurry surface, noisy ISO, deformed fingers'],
    ctaSuggestions: ['Acabamento impecável', 'Sinta a qualidade', 'Garanta o seu'],
    tags: ['macro', 'mao', 'acabamento', 'textura']
  },
  {
    code: '/before-after',
    label: 'Before & After Transformation',
    category: 'affiliate_marketplace',
    description: 'Comparativo visual de transformação clara e impacto imediato.',
    bestFor: ['Produtos de limpeza', 'Maquiagem e skincare', 'Organização de ambientes', 'Restauração'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    channel: 'Generic',
    visualDNA: ['Split screen or side-by-side comparative layout', 'Identical lighting and framing', 'Dramatic clear transformation'],
    promptAdditions: ['Side-by-side before and after comparison, identical camera angle and lighting, dramatic tangible improvement.'],
    negativePromptAdditions: ['unrelated before and after frames, mismatched lighting, fake exaggerated artifacts'],
    ctaSuggestions: ['O resultado fala por si!', 'Veja a diferença em segundos', 'Testado e aprovado'],
    tags: ['antes-depois', 'comparativo', 'transformacao', 'resultado']
  }
];
