import { PresetDefinition } from '../types';

export const BACKGROUND_PRESETS: PresetDefinition[] = [
  {
    code: '/white-seamless',
    label: 'Pure Seamless White Cyclorama',
    category: 'background_scene',
    description: 'Fundo infinito branco puro de estúdio sem emendas visíveis e com sombra suave no chão.',
    bestFor: ['E-commerce', 'Catálogos', 'Marketplaces'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Solid white cyclorama curve', 'Soft ground contact shadow', 'Zero distracting environmental elements'],
    promptAdditions: ['Pure seamless white cyclorama studio backdrop, infinite clean white floor, realistic soft contact shadow, zero edge artifacts.'],
    negativePromptAdditions: ['gray tint, visible wall corner, scuffed floor'],
    tags: ['fundo-branco', 'ciclorama', 'sem-emenda', 'estudio']
  },
  {
    code: '/clean-table',
    label: 'Clean Tabletop & Counter Surface',
    category: 'background_scene',
    description: 'Bancada limpa de madeira clara, mármore branco ou cimento queimado.',
    bestFor: ['Produtos em mesa', 'Cosméticos', 'Café e gastronomia'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Clean minimalist countertop material (light oak or white marble)', 'Soft natural room falloff', 'Warm daylight'],
    promptAdditions: ['Pristine clean tabletop surface made of honed white marble and light Scandinavian oak, soft room blur behind, warm morning light.'],
    negativePromptAdditions: ['messy plates, dirty table, clutter'],
    tags: ['bancada', 'mesa-limpa', 'marmore', 'madeira-clara']
  },
  {
    code: '/studio-backdrop',
    label: 'Textured Studio Canvas Backdrop',
    category: 'background_scene',
    description: 'Pano de fundo de estúdio texturizado pintado à mão (estilo Oliphant) em cinza, terracota ou azul marinho.',
    bestFor: ['Retratos editoriais', 'Moda de luxo', 'Campanhas de perfume'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Hand-painted fine art canvas backdrop', 'Subtle textured mottling and tonal variation', 'Prestigious studio portrait look'],
    promptAdditions: ['Hand-painted textured canvas studio backdrop, rich mottled gray-sage tones, fine art portrait studio setting.'],
    negativePromptAdditions: ['flat solid digital color, pixelated gradient'],
    tags: ['fundo-texturizado', 'oliphant', 'tela-pintada', 'fine-art']
  },
  {
    code: '/home-setting',
    label: 'Modern Aesthetic Living Home',
    category: 'background_scene',
    description: 'Ambiente residencial moderno, aconchegante e organizado com plantas e luz natural.',
    bestFor: ['UGC autêntico', 'Utilidades domésticas', 'Moda casual'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Tastefully decorated living space', 'Houseplants (Monstera, Ficus)', 'Warm neutral furniture with soft focus depth'],
    promptAdditions: ['Modern aesthetic home interior, clean minimalist decor, lush green houseplant in soft focus, warm sunlit living space.'],
    negativePromptAdditions: ['messy laundry, chaotic untidy room'],
    tags: ['casa', 'home-setting', 'aconchegante', 'decoracao']
  },
  {
    code: '/bathroom-setting',
    label: 'Luxury Spa Bathroom Vanity',
    category: 'background_scene',
    description: 'Banheiro de spa com bancada de mármore, espelho iluminado por LED e toalhas enroladas.',
    bestFor: ['Skincare', 'Xampus e sabonetes', 'Escovas e higiene'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['White marble vanity countertop with modern matte black faucet', 'Backlit vanity mirror glow', 'Fluffy rolled spa towels'],
    promptAdditions: ['Luxury modern spa bathroom vanity setting, white Carrara marble counter, warm backlit mirror illumination, serene atmosphere.'],
    negativePromptAdditions: ['dirty sink, water stains, moldy grout'],
    tags: ['banheiro', 'spa', 'espelho-led', 'skincare']
  },
  {
    code: '/bedroom-setting',
    label: 'Cozy Aesthetic Bedroom',
    category: 'background_scene',
    description: 'Quarto aconchegante com lençóis de linho macios, luz suave e cabeceira moderna.',
    bestFor: ['Pijamas e lingerie', 'Livros', 'Produtos de sono e relaxamento'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Plush linen bedding in neutral tones', 'Soft diffused bedside lamp glow', 'Relaxing intimate atmosphere'],
    promptAdditions: ['Cozy aesthetic bedroom setting, soft crumpled white linen sheets, warm bedside lamp glow, intimate peaceful ambience.'],
    negativePromptAdditions: ['messy unmade dirty bed, harsh flash'],
    tags: ['quarto', 'cama', 'linho', 'aconchego', 'sono']
  },
  {
    code: '/living-room-setting',
    label: 'Contemporary Living Room',
    category: 'background_scene',
    description: 'Sala de estar contemporânea com sofá de boucle bege, mesa de centro de madeira e tapete macio.',
    bestFor: ['Eletrônicos de sala', 'Decoração', 'Moda casual chic'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Curved bouclé sofa', 'Low profile designer coffee table', 'Floor-to-ceiling sheer curtains'],
    promptAdditions: ['Contemporary designer living room, cream bouclé sofa, minimalist coffee table, sheer floor-to-ceiling curtains with soft sunlight.'],
    negativePromptAdditions: ['dated 80s floral sofa, crowded junk'],
    tags: ['sala', 'sofa-boucle', 'living', 'design-interior']
  },
  {
    code: '/office-setting',
    label: 'Sleek Modern Executive Office',
    category: 'background_scene',
    description: 'Escritório executivo moderno com laptop, vista panorâmica da cidade e iluminação profissional.',
    bestFor: ['Negócios', 'Notebooks e tecnologia', 'Moda executiva/alfaiataria'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Minimalist walnut desk with aluminum laptop', 'Large glass windows overlooking city skyscrapers', 'Clean professional executive vibe'],
    promptAdditions: ['Sleek modern executive office, minimalist wooden desk, panoramic glass window with blurred city skyline, sharp professional atmosphere.'],
    negativePromptAdditions: ['tangled wires, chaotic paper stacks'],
    tags: ['escritorio', 'office', 'executivo', 'skyline', 'negocios']
  },
  {
    code: '/urban-street',
    label: 'Chic European City Street',
    category: 'background_scene',
    description: 'Rua charmosa de cidade europeia (Paris/Milão) com arquitetura clássica e cafés na calçada.',
    bestFor: ['Street style', 'Bolsas e calçados', 'Óculos e casacos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Haussmannian classic Parisian facades', 'Cobblestone or clean sidewalk with sidewalk bistro table', 'Soft afternoon sunlight'],
    promptAdditions: ['Chic European city street setting, classic limestone Parisian building facade, quaint outdoor cafe table in blurred background, warm daylight.'],
    negativePromptAdditions: ['trash cans, construction work, ugly graffiti'],
    tags: ['rua-europeia', 'paris', 'calcada', 'cafe', 'street-style']
  },
  {
    code: '/luxury-interior',
    label: 'Penthouse & Luxury Interior',
    category: 'background_scene',
    description: 'Interior de cobertura de luxo com detalhes em latão dourado, mármore negro e obras de arte contemporâneas.',
    bestFor: ['Joias finas', 'Alta costura', 'Relógios milionários'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Polished black Marquina marble', 'Brushed brass architectural trim', 'Curated modern sculpture and dramatic ambient lighting'],
    promptAdditions: ['High-end luxury penthouse interior, black marble surfaces with gold brass accents, gallery-level modern art, opulent sophisticated aesthetic.'],
    negativePromptAdditions: ['cheap laminate, plastic furniture'],
    tags: ['luxo-interior', 'cobertura', 'penthouse', 'ouro', 'marmore-negro']
  },
  {
    code: '/storefront',
    label: 'Designer Flagship Storefront',
    category: 'background_scene',
    description: 'Fachada e vitrine de loja de grife internacional com iluminação de boutique e arquitetura minimalista.',
    bestFor: ['Varejo de moda', 'Campanhas de marca', 'Apresentação de coleção'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Minimalist travertine and glass storefront facade', 'Warm interior boutique illumination through crystal glass', 'Chic luxury retail street'],
    promptAdditions: ['Designer luxury flagship storefront, grand glass and travertine facade, warm welcoming boutique interior lighting, prestigious avenue.'],
    negativePromptAdditions: ['rundown strip mall, neon tacky signs'],
    tags: ['loja', 'vitrine', 'storefront', 'grife', 'boutique']
  },
  {
    code: '/cinematic-city',
    label: 'Cinematic Night City Skyline',
    category: 'background_scene',
    description: 'Metrópole à noite com arranha-céus iluminados, luzes de tráfego e reflexos urbanos.',
    bestFor: ['Capas cinematográficas', 'Carros', 'Moda noturna'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Luminous skyscraper skyline at blue hour', 'Glowing traffic light trails below', 'Deep blue and gold chromatic palette'],
    promptAdditions: ['Cinematic night cityscape backdrop, glowing skyscraper windows, warm bokeh traffic light streaks, deep twilight blue sky.'],
    negativePromptAdditions: ['empty black void, pixelated sky'],
    tags: ['cidade-noturna', 'skyline', 'arranha-ceus', 'noite-urbana']
  },
  {
    code: '/rainy-street',
    label: 'Rain-Slicked Moody Street',
    category: 'background_scene',
    description: 'Rua molhada pela chuva com reflexos de postes e neon no asfalto reluzente.',
    bestFor: ['Neo-noir', 'Moda de inverno', 'Mistério e ação'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Wet glistening asphalt reflecting warm streetlights and neon', 'Atmospheric rain mist in air', 'Moody reflections'],
    promptAdditions: ['Atmospheric rain-slicked asphalt street at dusk, glistening reflections of streetlights in puddles, gentle misty rain, moody depth.'],
    negativePromptAdditions: ['dry sunny day, harsh daylight'],
    tags: ['chuva', 'asfalto-molhado', 'reflexo-chuva', 'moody']
  },
  {
    code: '/minimal-room',
    label: 'Architectural Minimalist Concrete Room',
    category: 'background_scene',
    description: 'Espaço arquitetônico com concreto aparente, luz zenital e vazios geométricos.',
    bestFor: ['Design conceitual', 'Sneakers', 'Arte contemporânea'],
    compatibleModules: ['creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Smooth raw concrete walls (Tadao Ando style)', 'Geometric cutouts allowing sharp sunbeams', 'Monastic pure minimalism'],
    promptAdditions: ['Architectural minimalist concrete gallery space in style of Tadao Ando, clean geometry, dramatic angular sunbeam, serene vast space.'],
    negativePromptAdditions: ['busy decorations, messy carpet'],
    tags: ['concreto', 'minimalismo-puro', 'arquitetura', 'tadao-ando']
  },
  {
    code: '/ecommerce-background',
    label: 'Soft Pastel E-Commerce Gradient',
    category: 'background_scene',
    description: 'Fundo em degradê suave em tons pastéis (bege, rosa seco, azul bebê) para e-commerce moderno.',
    bestFor: ['Produtos femininos', 'Cosméticos', 'Acessórios fofos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Soft pastel gradient backdrop (warm cream to blush pink)', 'Gentle floor shadow', 'Clean commercial e-commerce look'],
    promptAdditions: ['Soft pastel gradient studio background (warm blush to almond cream), gentle diffused floor shadow, modern clean e-commerce look.'],
    negativePromptAdditions: ['dirty floor, neon harsh clash'],
    tags: ['pastel', 'degrade', 'ecommerce-suave', 'feminino']
  }
];
