import { PresetDefinition } from '../types';

export const BEAUTY_PRESETS: PresetDefinition[] = [
  {
    code: '/beauty-demo',
    label: 'Beauty & Skincare Demo',
    category: 'beauty_cosmetics',
    description: 'Demonstração de produtos de beleza com pele viçosa, iluminação ring-light e textura clara.',
    bestFor: ['Cremes faciais', 'Séruns', 'Maquiagem diária'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Dewy radiant skin finish', 'Soft wrap-around beauty lighting', 'Clean pastel aesthetic'],
    promptAdditions: ['High-end beauty cosmetic demo, model with luminous radiant skin, soft beauty dish lighting, clean aesthetic bathroom vanity.'],
    negativePromptAdditions: ['oily greasy shine, heavy artificial pore smoothing, cakey makeup'],
    tags: ['beleza', 'skincare', 'pele', 'cosmetico', 'demo']
  },
  {
    code: '/beauty-editorial',
    label: 'High-Fashion Beauty Editorial',
    category: 'beauty_cosmetics',
    description: 'Close de beleza de revista com maquiagem artística e pele hiper-detalhada.',
    bestFor: ['Campanhas de batom', 'Sombras e delineados', 'Fotografia de beleza de luxo'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Macro facial crop', 'Visible authentic skin pores without blemishes', 'Bold artistic color contrast'],
    promptAdditions: ['High fashion beauty editorial close-up, razor-sharp focus on glossy lips and eye makeup, perfect natural skin texture, dramatic studio beauty lighting.'],
    negativePromptAdditions: ['plastic airbrushed blur, smeared makeup artifacts, dead eyes'],
    tags: ['editorial-beleza', 'maquiagem', 'batom', 'luxo']
  },
  {
    code: '/fragrance-presentation',
    label: 'Luxury Fragrance & Perfume',
    category: 'beauty_cosmetics',
    description: 'Apresentação etérea de perfume com respingos, névoa e iluminação dourada/cristal.',
    bestFor: ['Perfumes masculinos e femininos', 'Frascos de vidro facetado', 'Água de colônia'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Crystal glass refractive caustic patterns', 'Delicate mist or water splash around base', 'Ethereal luxury mood'],
    promptAdditions: ['Luxury perfume commercial photograph, glass bottle with glowing amber liquid, fine mist particles in air, luminous caustics and opulent mood.'],
    negativePromptAdditions: ['dirty glass, cloudy liquid, flat background'],
    tags: ['perfume', 'fragrancia', 'vidro', 'nevoa', 'luxo']
  },
  {
    code: '/skincare-routine',
    label: 'Skincare Routine Step-by-Step',
    category: 'beauty_cosmetics',
    description: 'Passo a passo da rotina facial: limpeza, hidratação, sérum e proteção solar.',
    bestFor: ['Rotinas de cuidados', 'Carrosséis de skincare', 'Vídeos de passo a passo'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'carousel'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Clean bathroom vanity environment', 'Drops of serum applied to cheekbone', 'Relaxed zen self-care mood'],
    promptAdditions: ['Skincare routine demonstration, dropper applying translucent serum droplet to glowing cheek, clean spa-like morning light.'],
    negativePromptAdditions: ['messy background, spilled liquid, harsh flash'],
    tags: ['skincare', 'rotina', 'serum', 'spa']
  },
  {
    code: '/makeup-closeup',
    label: 'Makeup Application Close-Up',
    category: 'beauty_cosmetics',
    description: 'Enquadramento fechado no pincel aplicando blush, iluminador ou sombra.',
    bestFor: ['Pincéis de maquiagem', 'Sombras e blushes', 'Tutorias de aplicação'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Extreme macro of cosmetic brush bristling against skin', 'Airy pigment dust particle effect', 'Precision focus'],
    promptAdditions: ['Macro beauty shot of cosmetic brush applying velvety blush powder to cheekbone, fine airborne pigment particles, ultra-fine focus.'],
    negativePromptAdditions: ['clumpy powder, deformed brush, blurry skin'],
    tags: ['pincel', 'maquiagem', 'aplicacao', 'macro']
  },
  {
    code: '/self-care-angle',
    label: 'Self-Care & Wellness Vibe',
    category: 'beauty_cosmetics',
    description: 'Atmosfera de spa, velas aromáticas, toalha branca macia e bem-estar.',
    bestFor: ['Velas', 'Óleos corporais', 'Sais de banho', 'Bem-estar'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Warm candlelight accents', 'Plush white cotton towels and botanical elements', 'Calming eucalyptus/lavender green accents'],
    promptAdditions: ['Cozy wellness and self-care aesthetic, warm soothing candle glow, fluffy white spa towels, tranquil natural daylight.'],
    negativePromptAdditions: ['cold blue sterile light, synthetic plastic look'],
    tags: ['autocuidado', 'spa', 'vela', 'oleo', 'relaxamento']
  },
  {
    code: '/sensory-appeal',
    label: 'Sensory Cosmetic Appeal',
    category: 'beauty_cosmetics',
    description: 'Foco na experiência sensorial: cremosidade densa, gel refrescante e sensorialidade.',
    bestFor: ['Hidratantes corporais', 'Máscaras de argila', 'Bálsamos labiais'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sculpted cream swirls', 'Glossy hydration highlights', 'Tactile finger swatch'],
    promptAdditions: ['Ultra-sensory cosmetic composition, thick luxurious cream swirl with soft light passing through, dewy freshness and rich viscosity.'],
    negativePromptAdditions: ['dry matte look, lumpy uneven texture'],
    tags: ['sensorial', 'creme', 'viscosidade', 'hidratacao']
  },
  {
    code: '/gift-idea',
    label: 'Beauty Gift Set & Unwrapping',
    category: 'beauty_cosmetics',
    description: 'Caixa de presente com laço de cetim, papel de seda e produtos dispostos com carinho.',
    bestFor: ['Datas comemorativas (Dia das Mães, Namorados)', 'Kits de Natal', 'Edições de presente'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Elegant gift packaging with satin ribbon', 'Products nested in custom tissue insert', 'Celebratory warm ambient lighting'],
    promptAdditions: ['Luxury beauty gift set showcase, opened gift box with shimmering silk ribbon, perfectly arranged cosmetic bottles, festive warmth.'],
    negativePromptAdditions: ['torn box, cheap plastic packaging, crumpled tissue'],
    tags: ['presente', 'kit', 'dia-das-maes', 'natal', 'laco']
  },
  {
    code: '/beauty-consultant',
    label: 'Beauty Consultant Recommendation',
    category: 'beauty_cosmetics',
    description: 'Estilo consultora/esteticista profissional recomendando o produto com jaleco ou look clean.',
    bestFor: ['Dermocosméticos', 'Consultoras Natura/Avon/Boticário', 'Estética facial'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'copy_master', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Professional clinic or clean studio background', 'Confident friendly consultant posture', 'Product held respectfully'],
    promptAdditions: ['Professional beauty consultant in a minimalist modern aesthetic clinic holding skincare product, authoritative and warm demeanor.'],
    negativePromptAdditions: ['intimidating hospital vibe, messy desk'],
    tags: ['consultora', 'dermocosmetico', 'clinica', 'autoridade']
  },
  {
    code: '/consultora-style',
    label: 'Consultora de Beleza Amiga',
    category: 'beauty_cosmetics',
    description: 'Estilo acolhedor da revendedora experiente apresentando os lançamentos de catálogo.',
    bestFor: ['Revenda de cosméticos', 'Demonstração de perfumes', 'Kits prontos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Warm homely setup with flower vase', 'Products displayed on organized tray', 'Affectionate welcoming lighting'],
    promptAdditions: ['Warm Brazilian beauty reseller table presentation, stylish cosmetic bottles on decorative gold tray, welcoming natural light.'],
    negativePromptAdditions: ['cold corporate atmosphere, disorganized clutter'],
    tags: ['consultora-amiga', 'revendedora', 'catalogo', 'acolhedor']
  },
  {
    code: '/product-on-skin',
    label: 'Product Swatch on Skin',
    category: 'beauty_cosmetics',
    description: 'Swatches de cores (batons, bases, corretivos) no antebraço ou rosto sob luz neutra.',
    bestFor: ['Paletas de sombra', 'Tons de base e corretivo', 'Batons e gloses'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Clean forearm with multiple smooth cosmetic swipes', 'Accurate chromatic distinction between shades', 'Diffused neutral light'],
    promptAdditions: ['Cosmetic shade swatches on clean forearm, distinct saturated pigments (nude, rose, berry), smooth opaque application, neutral 5500K lighting.'],
    negativePromptAdditions: ['patchy uneven streaks, color bleeding, inaccurate skin tone'],
    tags: ['swatch', 'pele', 'tons', 'base', 'batom']
  },
  {
    code: '/texture-display',
    label: 'Texture Smear & Palette Art',
    category: 'beauty_cosmetics',
    description: 'Espatulada artística de base ou creme em placa de vidro ou mármore.',
    bestFor: ['Fotografia conceitual de produto', 'Páginas de fórmula', 'Header de e-commerce'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Thick textured spatula smear across white marble or clear acrylic', 'Micro-droplets and rich body', 'Studio rim light'],
    promptAdditions: ['Artistic cosmetic texture smear on white Carrara marble, thick sculpted swipe of nourishing face cream, dramatic angled light.'],
    negativePromptAdditions: ['flat smudge, dirty fingerprint, dull lighting'],
    tags: ['espatula', 'textura', 'marmore', 'conceitual']
  },
  {
    code: '/closeup-application',
    label: 'Close-Up Lip Gloss & Eye Application',
    category: 'beauty_cosmetics',
    description: 'Aplicação em tempo real de gloss labial com aplicador suave e brilho espelhado.',
    bestFor: ['Gloss labial', 'Máscara de cílios', 'Iluminador'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Macro lips framing', 'Doe-foot applicator gliding across lower lip', 'High-gloss lacquer reflection'],
    promptAdditions: ['Extreme close-up of glossy lip tint application, doe-foot wand gliding over plump lips, mirror-like shine and glass-skin perfection.'],
    negativePromptAdditions: ['chapped dry lips, runny globs, clumsy hand placement'],
    tags: ['gloss', 'aplicador', 'labios', 'macro-aplicacao']
  }
];
