import { PresetDefinition } from '../types';

export const CAMERA_PRESETS: PresetDefinition[] = [
  {
    code: '/close-up',
    label: 'Close-Up Shot',
    category: 'camera_angle',
    description: 'Plano fechado no rosto ou objeto principal com fundo suavemente desfocado.',
    bestFor: ['Expressões faciais', 'Detalhes do produto', 'Planos de reação'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['85mm portrait focal length', 'Tight framing from shoulders to top of head', 'Smooth bokeh falloff'],
    promptAdditions: ['Tight close-up shot, 85mm lens, sharp focus on subject facial expression, creamy soft bokeh background.'],
    negativePromptAdditions: ['wide shot, full body, distorted lens'],
    tags: ['close-up', 'plano-fechado', '85mm', 'rosto']
  },
  {
    code: '/extreme-close-up',
    label: 'Extreme Close-Up (ECU)',
    category: 'camera_angle',
    description: 'Plano detalhe extremo focado nos olhos, lábios ou micro-mecanismos.',
    bestFor: ['Olhares intensos', 'Texturas de maquiagem', 'Engrenagens e joias'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['100mm macro lens', 'Framing cropped tightly on eyes or lips', 'Razor-thin depth of field'],
    promptAdditions: ['Extreme close-up shot focusing solely on intense eyes and eyelashes, crystalline corneal reflections, ultra-shallow depth of field.'],
    negativePromptAdditions: ['full face, wide perspective, blurry eyes'],
    tags: ['extreme-close-up', 'olhos', 'macro', 'detalhe-extremo']
  },
  {
    code: '/medium-shot',
    label: 'Medium Shot (Waist Up)',
    category: 'camera_angle',
    description: 'Plano médio da cintura para cima, ideal para diálogo e interação com produto.',
    bestFor: ['Apresentadores', 'Provador de roupas', 'Diálogos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['50mm standard focal length', 'Waist-up framing showing hands and torso', 'Natural perspective'],
    promptAdditions: ['Medium shot framed from the waist up, 50mm natural perspective, clear posture and hand gestures, balanced background depth.'],
    negativePromptAdditions: ['extreme close-up, cropped hands awkwardly'],
    tags: ['medium-shot', 'plano-medio', 'cintura-cima', '50mm']
  },
  {
    code: '/wide-shot',
    label: 'Wide Establishing Shot',
    category: 'camera_angle',
    description: 'Plano aberto mostrando o sujeito completo inserido no ambiente/cenário.',
    bestFor: ['Localização de cena', 'Outfits de corpo inteiro', 'Arquitetura'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['24mm wide angle lens', 'Full body visible with generous surrounding environment', 'Deep depth of field'],
    promptAdditions: ['Wide establishing shot, 24mm lens, full-body subject placed harmoniously within expansive architectural environment.'],
    negativePromptAdditions: ['tight crop, fish-eye distortion, cropped shoes'],
    tags: ['wide-shot', 'plano-aberto', 'full-body', 'cenario']
  },
  {
    code: '/top-shot',
    label: 'Top Angle / Overhead Shot',
    category: 'camera_angle',
    description: 'Câmera posicionada diretamente no teto apontando 90 graus para baixo.',
    bestFor: ['Composições de mesa', 'Padrões geométricos', 'Visualização aérea'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Strict 90-degree overhead angle', 'Flat geometric plane', 'Even lighting distribution'],
    promptAdditions: ['Top-down 90-degree overhead camera angle, direct bird-eye perspective, geometric symmetry.'],
    negativePromptAdditions: ['tilted angled camera'],
    tags: ['top-shot', 'overhead', '90-graus', 'zenital']
  },
  {
    code: '/front-shot',
    label: 'Direct Frontal Shot',
    category: 'camera_angle',
    description: 'Câmera perfeitamente alinhada na altura dos olhos e centralizada frontalmente.',
    bestFor: ['Retratos solenes (estilo Wes Anderson)', 'Passaporte/Lookbook', 'Simetria'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Eye-level axis', 'Perfect bilateral symmetry', 'Direct forward gaze'],
    promptAdditions: ['Direct frontal eye-level camera shot, strict symmetrical framing in style of Wes Anderson, centered composition.'],
    negativePromptAdditions: ['asymmetrical angle, high/low tilt'],
    tags: ['frontal', 'simetria', 'olho-no-olho', 'wes-anderson']
  },
  {
    code: '/profile-shot',
    label: 'Side Profile Shot (90°)',
    category: 'camera_angle',
    description: 'Perfil lateral estrito mostrando silhueta da mandíbula, nariz e postura.',
    bestFor: ['Óculos de sol', 'Brincos e fones', 'Retratos conceituais'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Strict 90-degree side profile', 'Clean silhouette contour', 'Focused rim light on edge of profile'],
    promptAdditions: ['Strict 90-degree side profile portrait, crisp silhouette contour of jawline and nose, sculptural edge rim light.'],
    negativePromptAdditions: ['semi-turned 3/4 face, frontal gaze'],
    tags: ['perfil', 'lateral', 'silhueta', 'mandibula']
  },
  {
    code: '/three-quarter-shot',
    label: 'Classic 3/4 Angle Shot',
    category: 'camera_angle',
    description: 'Ângulo em três quartos (45°), o mais lisonjeiro para rostos e produtos.',
    bestFor: ['Retratos profissionais', 'Carros e produtos', 'Moda'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['45-degree angle to subject', 'Shows both frontal face/product and side depth', 'Flattering dimensional perspective'],
    promptAdditions: ['Classic three-quarter 3/4 angle shot, natural dimensional perspective showing front and depth simultaneously, flattering depth of field.'],
    negativePromptAdditions: ['flat front view, extreme distortion'],
    tags: ['3-4', 'tres-quartos', '45-graus', 'dimensional']
  },
  {
    code: '/hero-angle',
    label: 'Hero Power Angle',
    category: 'camera_angle',
    description: 'Ângulo de baixo para cima com lente média transmitindo poder, liderança e autoridade.',
    bestFor: ['Líderes', 'Super-heróis', 'Carros potentes', 'Produtos premium'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Low-angle perspective looking up at subject', 'Wide shoulders, confident chin raised', 'Sky or dramatic ceiling background'],
    promptAdditions: ['Hero power angle looking slightly upward, subject exudes commanding authority and confidence, monumental perspective.'],
    negativePromptAdditions: ['looking down, timid hunched posture'],
    tags: ['hero-angle', 'poder', 'autoridade', 'baixo-para-cima']
  },
  {
    code: '/low-angle',
    label: 'Low Angle (Contra-Plongée)',
    category: 'camera_angle',
    description: 'Câmera no nível do chão ou cintura apontando para cima, ampliando a escala vertical.',
    bestFor: ['Arranha-céus', 'Monstros', 'Tênis e passadas', 'Imponência'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Ground level camera position', 'Exaggerated vertical perspective lines', 'Dramatic stature'],
    promptAdditions: ['Dramatic low-angle contra-plongée camera view from near ground level, vertical vanishing lines, awe-inspiring scale.'],
    negativePromptAdditions: ['high angle looking down, bird eye'],
    tags: ['low-angle', 'contra-plongee', 'chao', 'imponente']
  },
  {
    code: '/high-angle',
    label: 'High Angle (Plongée)',
    category: 'camera_angle',
    description: 'Câmera elevada olhando para baixo, criando sensação de intimidade, vulnerabilidade ou visão geral.',
    bestFor: ['Mesas de trabalho', 'Multidões', 'Cenas contemplativas'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Elevated camera 45 degrees looking downward', 'Clear view of floor/table surface around subject', 'Intimate perspective'],
    promptAdditions: ['High-angle plongée shot looking downward at subject, expansive view of surrounding floor surface, contemplative mood.'],
    negativePromptAdditions: ['ground level, upward tilt'],
    tags: ['high-angle', 'plongee', 'de-cima', 'intimo']
  },
  {
    code: '/macro-shot',
    label: 'Macro 1:1 Precision',
    category: 'camera_angle',
    description: 'Lente macro com proporção 1:1 revelando partículas, texturas e detalhes invisíveis a olho nu.',
    bestFor: ['Gotas de água', 'Fibras de tecido', 'Pupilas', 'Joias'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Macro optical magnification', 'Ultra crisp micro details', 'Dreamy micro-specular bokeh circles'],
    promptAdditions: ['Macro 1:1 magnification photograph, razor-sharp focus on microscopic surface details, ethereal background bokeh balls.'],
    negativePromptAdditions: ['blurry magnification, noisy grain'],
    tags: ['macro', '1-1', 'microscopio', 'detalhe']
  },
  {
    code: '/push-in',
    label: 'Slow Push-In Dolly Motion',
    category: 'camera_angle',
    description: 'Sensação de aproximação gradual da câmera em direção ao sujeito, aumentando a tensão.',
    bestFor: ['Momentos de revelação', 'Aumento de foco', 'Storyboards de vídeo'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon'],
    outputModes: ['storyboard', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Subtle motion lines converging towards center subject', 'Increasing subject dominance', 'Cinematic track dolly feel'],
    promptAdditions: ['Cinematic slow dolly push-in camera motion towards subject, building intense dramatic focus and intimacy.'],
    negativePromptAdditions: ['static flat shot, shaky camera'],
    tags: ['push-in', 'dolly', 'aproximacao', 'tensao']
  },
  {
    code: '/pull-back',
    label: 'Epic Pull-Back Reveal',
    category: 'camera_angle',
    description: 'Câmera recuando para revelar o contexto grandioso ao redor do personagem.',
    bestFor: ['Finais de cena', 'Revelação de cenário', 'Solidão épica'],
    compatibleModules: ['cinematic_engine', 'creative_director'],
    outputModes: ['storyboard', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Receding camera motion lines', 'Expanding environmental horizon around subject', 'Grand scale reveal'],
    promptAdditions: ['Epic camera pull-back dolly motion, transitioning from intimate subject to vast awe-inspiring surrounding world.'],
    negativePromptAdditions: ['tight crop only, zoomed in'],
    tags: ['pull-back', 'recuo', 'revelacao', 'escala']
  },
  {
    code: '/dolly-in',
    label: 'Smooth Dolly-In Track',
    category: 'camera_angle',
    description: 'Movimento fluido sobre trilhos em direção ao objeto com estabilização de cinema.',
    bestFor: ['Apresentação de carros', 'Entrada de personagens', 'Comerciais de TV'],
    compatibleModules: ['cinematic_engine', 'creative_director'],
    outputModes: ['storyboard', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Gliding smooth optical perspective', 'Parallax shift between foreground and background', 'Master cinematography'],
    promptAdditions: ['Smooth track dolly-in camera movement, rich foreground-to-background parallax shift, Hollywood production value.'],
    negativePromptAdditions: ['handheld jitter, jerky movement'],
    tags: ['dolly-in', 'trilho', 'paralaxe', 'estabilizado']
  },
  {
    code: '/handheld',
    label: 'Dynamic Handheld Camera',
    category: 'camera_angle',
    description: 'Câmera na mão com micro-movimentos orgânicos transmitindo urgência e realismo cru.',
    bestFor: ['Cenas de perseguição', 'Documentários', 'UGC imersivo', 'Ação realista'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Organic subtle camera shake/tilt', 'Visceral documentary feel', 'Immediate raw immersion'],
    promptAdditions: ['Visceral documentary-style handheld camera frame, organic subtle camera movement, raw authentic immersion.'],
    negativePromptAdditions: ['sterile robotic gimbal look, lifeless lockoff'],
    tags: ['camera-na-mao', 'handheld', 'documentario', 'realismo', 'acao']
  },
  {
    code: '/gimbal-smooth',
    label: 'Gimbal Steadicam Glide',
    category: 'camera_angle',
    description: 'Movimento contínuo e suave como se a câmera estivesse flutuando no ar.',
    bestFor: ['Tours em mansões', 'Caminhadas de moda', 'Comerciais automotivos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon'],
    outputModes: ['storyboard', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Weightless floating camera trajectory', 'Perfect horizontal horizon balance', 'Seamless tracking motion'],
    promptAdditions: ['Steadicam gimbal floating camera glide, perfectly stabilized fluid motion tracking subject effortlessly.'],
    negativePromptAdditions: ['shaky handheld, tilted crooked horizon'],
    tags: ['gimbal', 'steadicam', 'flutuante', 'estabilizado']
  },
  {
    code: '/continuous-take',
    label: 'One-Shot Continuous Long Take',
    category: 'camera_angle',
    description: 'Sensação de plano-sequência sem cortes conectando múltiplos ambientes com fluidez.',
    bestFor: ['Planos-sequência', 'Storyboards fluidos', 'Cinematografia autoral'],
    compatibleModules: ['cinematic_engine', 'creative_director'],
    outputModes: ['storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Fluid continuous choreography', 'Seamless lighting transitions between spaces', 'Dynamic pacing'],
    promptAdditions: ['Cinematic continuous one-shot long take sequence, seamless unbroken camera flow through dynamic environment.'],
    negativePromptAdditions: ['hard cuts, disjointed jumpy framing'],
    tags: ['plano-sequencia', 'one-shot', 'long-take', 'sem-cortes']
  },
  {
    code: '/fast-cut',
    label: 'Fast-Cut High Energy Edit',
    category: 'camera_angle',
    description: 'Ritmo acelerado com cortes rápidos de 0.5s mostrando múltiplos ângulos em fração de segundos.',
    bestFor: ['TikTok virais', 'Comerciais de tênis/esportes', 'Trailers de ação'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Rapid alternating angles (macro, wide, close)', 'High visual kinetic energy', 'Motion blur transition frames'],
    promptAdditions: ['Fast-paced kinetic camera cut, high-energy snap visual angle transition, intense dynamic tempo.'],
    negativePromptAdditions: ['slow boring static scene, relaxed calm vibe'],
    tags: ['corte-rapido', 'fast-cut', 'energia', 'esporte', 'dinamico']
  },
  {
    code: '/slow-motion',
    label: 'Super Slow Motion (1000fps)',
    category: 'camera_angle',
    description: 'Super câmera lenta congelando gotas de água, tecidos voando no ar ou faíscas.',
    bestFor: ['Fluidos e respingos', 'Cabelo ao vento em moda', 'Comidas e explosões'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Frozen liquid droplets suspended in mid-air', 'Airy floating fabric ribbons', 'Razor sharp high shutter speed rendering'],
    promptAdditions: ['High-speed Phantom Flex 4K super slow-motion capture (1000fps), liquid droplets frozen crystal-clear mid-air, floating fabric elegance.'],
    negativePromptAdditions: ['motion smear blur, low shutter speed'],
    tags: ['slow-motion', 'camera-lenta', '1000fps', 'gotas', 'tecido']
  }
];
