import { PresetDefinition } from '../types';

export const CINEMATIC_PRESETS: PresetDefinition[] = [
  {
    code: '/movieposter',
    label: 'Cinematic Movie Poster',
    category: 'cinematic_poster',
    description: 'Pôster cinematográfico vertical com iluminação dramática, hierarquia de título e billing block.',
    bestFor: ['Pôsteres de filmes', 'Capas teatrais', 'Key art de produções', 'Divulgação de lançamentos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'visual_reference', 'image_generator', 'virtual_tryon'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: [
      'Vertical theatrical movie poster layout',
      'Strong central protagonist composition with dramatic rim light',
      'Theatrical chiaroscuro lighting and atmospheric haze/smoke',
      'Clear space reserved for bold title hierarchy on top or center-bottom',
      'Billing block / movie credit text space at bottom edge'
    ],
    promptAdditions: [
      'Create a vertical theatrical cinematic movie poster with dramatic high-contrast lighting, strong central character composition, bold title hierarchy, atmospheric volumetric haze, and professional key art layout with billing block space at bottom.'
    ],
    negativePromptAdditions: [
      'poor typography, unreadable title, distorted face, messy credits, random logos, amateur layout, cartoonish vector'
    ],
    tags: ['filme', 'poster', 'cinema', 'key-art', 'hollywood', 'dramatico']
  },
  {
    code: '/cinematicposter',
    label: 'High-Impact Cinematic Poster',
    category: 'cinematic_poster',
    description: 'Pôster de alto impacto visual com paleta teal and orange e iluminação dramática.',
    bestFor: ['Filmes de ação', 'Séries de suspense', 'Capas de streaming'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Teal and orange cinematic color grading', 'Atmospheric particles, rain or embers in air', 'Anamorphic lens flare'],
    promptAdditions: ['High-impact cinematic blockbuster poster, complementary teal and orange palette, anamorphic lens flares, atmospheric dust and fog.'],
    negativePromptAdditions: ['flat daytime lighting, low resolution, washed out colors'],
    tags: ['cinematografico', 'teal-orange', 'flare', 'blockbuster']
  },
  {
    code: '/actionposter',
    label: 'Action & Explosive Poster',
    category: 'cinematic_poster',
    description: 'Pôster de ação com faíscas, estilhaços de vidro, dinamismo e pose heroica.',
    bestFor: ['Filmes de ação', 'Games de combate', 'Super-heróis'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Motion blur on background elements', 'Floating debris, sparks and lens fire', 'Determined warrior stance'],
    promptAdditions: ['Explosive high-octane action movie poster, dynamic hero in battle stance, flying sparks and shattered glass fragments, intense backlighting.'],
    negativePromptAdditions: ['static peaceful pose, smiling casually, dull colors'],
    tags: ['acao', 'explosao', 'faisca', 'heroi', 'combate']
  },
  {
    code: '/thrillerposter',
    label: 'Psychological Thriller Poster',
    category: 'cinematic_poster',
    description: 'Pôster de suspense psicológico com sombras alongadas, névoa e mistério envolvente.',
    bestFor: ['Suspense', 'Mistério policial', 'Dramas psicológicos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Desaturated eerie palette with single color pop (crimson/yellow)', 'Deep silhouettes and foggy back-alleys', 'Tense psychological atmosphere'],
    promptAdditions: ['Psychological thriller film poster, haunting silhouette emerging from dense mist, deep shadows, chilling color grading with selective red accent.'],
    negativePromptAdditions: ['cheerful sunshine, bright cheerful smiles'],
    tags: ['thriller', 'suspense', 'misterio', 'nevoa', 'psicologico']
  },
  {
    code: '/dramaposter',
    label: 'Emotional Drama Poster',
    category: 'cinematic_poster',
    description: 'Pôster focado na intensidade emocional dos personagens com iluminação intimista.',
    bestFor: ['Dramas aclamados', 'Biografias', 'Filmes autorais'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Intimate portrait lighting', 'Subtle 35mm film grain texture', 'Melancholic or reflective mood'],
    promptAdditions: ['Critically acclaimed drama movie poster, emotionally poignant close-up portrait, natural golden window light, 35mm film texture, profound mood.'],
    negativePromptAdditions: ['cartoony gloss, exaggerated caricature, neon flares'],
    tags: ['drama', 'emocional', 'autoral', '35mm', 'cinema']
  },
  {
    code: '/crimeposter',
    label: 'Crime & Detective Noir Poster',
    category: 'cinematic_poster',
    description: 'Estética policial com sobretudo, chuva na janela, fita de isolamento e luz de neon.',
    bestFor: ['Histórias de detetive', 'Máfia e crime organizado', 'Investigação'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Wet asphalt reflections', 'Venetian blind shadow patterns across face', 'Gritty detective trench coat aesthetic'],
    promptAdditions: ['Gritty crime investigation film poster, detective in rainy night street, neon sign reflecting on puddle, noir shadows, gripping tension.'],
    negativePromptAdditions: ['sunny beach, happy vacation vibe'],
    tags: ['crime', 'policial', 'detetive', 'noir', 'chuva']
  },
  {
    code: '/scifiposter',
    label: 'Sci-Fi & Cyberpunk Poster',
    category: 'cinematic_poster',
    description: 'Ficção científica com cidades futuristas, hologramas, neon ciano/magenta e naves.',
    bestFor: ['Ficção científica', 'Cyberpunk', 'Space opera', 'Tecnologia avançada'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Futuristic megacity silhouette with flying vehicles', 'Holographic UI glowing accents', 'Cyan, purple and electric blue lighting'],
    promptAdditions: ['Epic sci-fi movie poster, futuristic cybernetic skyline, glowing holographic overlays, cosmic deep space elements, cinematic grandeur.'],
    negativePromptAdditions: ['medieval fantasy props, rustic wood, low tech'],
    tags: ['sci-fi', 'cyberpunk', 'futurista', 'holograma', 'espaco']
  },
  {
    code: '/horrorposter',
    label: 'Horror & Paranormal Poster',
    category: 'cinematic_poster',
    description: 'Pôster de terror visceral com contrastes perturbadores, vultos e atmosfera gótica.',
    bestFor: ['Filmes de terror', 'Casas mal-assombradas', 'Ficção paranormal'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Low-key pitch black lighting with minimal specular rim', 'Eerie desaturated skin tone', 'Creepy atmospheric fog and vintage horror texture'],
    promptAdditions: ['Supernatural horror movie poster, chilling shadowy figure in darkened doorway, cold moonlight, distressed film grain, suffocating dread.'],
    negativePromptAdditions: ['cute cartoon ghosts, bright happy lighting'],
    tags: ['terror', 'horror', 'sobrenatural', 'escuro', 'medo']
  },
  {
    code: '/romanceposter',
    label: 'Romantic Cinema Poster',
    category: 'cinematic_poster',
    description: 'Pôster romântico com casal em contraluz, pôr do sol dourado e paleta aconchegante.',
    bestFor: ['Comédias românticas', 'Dramas de época', 'Histórias de amor'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Golden hour rim backlighting', 'Intimate couple profile or embrace', 'Dreamy soft focus bokeh and pastel sunset colors'],
    promptAdditions: ['Romantic cinema movie poster, couple in tender silhouette during golden sunset, warm amber flares, poetic emotional elegance.'],
    negativePromptAdditions: ['violent action, dark morbid blood, cold blue tones'],
    tags: ['romance', 'casal', 'por-do-sol', 'dourado', 'amor']
  },
  {
    code: '/mysteryposter',
    label: 'Mystery & Whodunnit Poster',
    category: 'cinematic_poster',
    description: 'Estilo "Knives Out" com mansão clássica, pistas escondidas e elenco de suspeitos.',
    bestFor: ['Mistérios clássicos', 'Whodunnit', 'Enigmas de assassinato'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Rich Victorian interior with mahogany and velvet', 'Dramatic key light on key clue object', 'Ensemble cast framing'],
    promptAdditions: ['Whodunnit mystery movie poster, grand gothic manor library, eccentric suspect ensemble in foreground, rich amber and emerald lighting.'],
    negativePromptAdditions: ['plain empty room, flat sterile modern office'],
    tags: ['misterio', 'whodunnit', 'mansao', 'pistas', 'enigma']
  },
  {
    code: '/spy-poster',
    label: 'Spy & Espionage Poster',
    category: 'cinematic_poster',
    description: 'Estética agente secreto (007/Mission Impossible) com smoking, armas silenciosas e capitais mundiais.',
    bestFor: ['Espionagem internacional', 'Agentes secretos', 'Missões táticas'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sleek tuxedo/stealth tactical gear', 'High-speed sports car or iconic European landmarks in background', 'Sharp laser-guided crosshair graphics'],
    promptAdditions: ['International spy thriller poster, sharp suited agent walking away from exploding luxury villa, slick cold metallic grading, 007 aesthetic.'],
    negativePromptAdditions: ['clumsy posture, casual beachwear, childish graphics'],
    tags: ['espiao', 'agente', '007', 'acao', 'luxo']
  },
  {
    code: '/noir-poster',
    label: 'Classic Black & White Noir',
    category: 'cinematic_poster',
    description: 'Pôster clássico preto e branco com iluminação expressionista, sombras de persiana e fumaça.',
    bestFor: ['Filmes noir clássicos', 'Estética vintage anos 40', 'Jazz e decadência urbana'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Monochrome rich silver gelatin black and white', 'Hard directional spot light slicing through dark room', 'Cigarette smoke swirls and fedora hat'],
    promptAdditions: ['Classic 1940s film noir poster, high-contrast black and white, dramatic Venetian blind shadow across eyes, fedora hat silhouette, smoky room.'],
    negativePromptAdditions: ['full RGB color, pastel tones, digital smoothness'],
    tags: ['noir', 'preto-branco', 'anos-40', 'sombra', 'classico']
  },
  {
    code: '/neo-noir',
    label: 'Neo-Noir & Cyber Rain',
    category: 'cinematic_poster',
    description: 'Noir contemporâneo (Blade Runner / John Wick) misturando neon vibrante com noites chuvosas.',
    bestFor: ['Neo-noir urbano', 'Assassinos profissionais', 'Mundo subterrâneo'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vibrant neon magenta, cyan and amber contrasting against pitch-black wet concrete', 'Heavy rainfall glistening under streetlights', 'Sharp tailored suit'],
    promptAdditions: ['Neo-noir movie poster in style of John Wick, lone figure standing in torrential Tokyo rain, glowing neon kanji reflections on wet pavement, hyper-stylish.'],
    negativePromptAdditions: ['daytime, dry sunny weather, washed out colors'],
    tags: ['neo-noir', 'john-wick', 'neon', 'chuva', 'estilo']
  },
  {
    code: '/teaserposter',
    label: 'Minimalist Teaser Poster',
    category: 'cinematic_poster',
    description: 'Pôster misterioso focado em um único símbolo icônico ou silhueta enigmática.',
    bestFor: ['Teasers de primeiro anúncio', 'Mistério e buzz pré-lançamento', 'Campanhas virais'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Minimalist single subject or artifact', 'Vast negative space around focal point', 'Cryptic tagline and release date only'],
    promptAdditions: ['Minimalist cinematic teaser poster, single mysterious artifact glowing in vast dark space, elegant enigmatic aura, high intrigue.'],
    negativePromptAdditions: ['crowded cluttered frame, 20 actors packed together'],
    tags: ['teaser', 'minimalista', 'misterio', 'simbolo', 'buzz']
  },
  {
    code: '/comingsoon',
    label: 'Coming Soon / Release Date Poster',
    category: 'cinematic_poster',
    description: 'Composição preparada para anúncio de data de estreia com tipografia imponente.',
    bestFor: ['Divulgação de estreias', 'Anúncio de temporadas', 'Contagem regressiva'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Impactful central visual', 'Clear bottom banner for "BREVEMENTE NOS CINEMAS" or date', 'Theatrical glow'],
    promptAdditions: ['Cinematic release announcement poster, hero artwork with prominent clean lower third reserved for release date, anticipation vibe.'],
    negativePromptAdditions: ['messy text overlap, low quality'],
    tags: ['estreia', 'coming-soon', 'data', 'lancamento']
  },
  {
    code: '/characterposter',
    label: 'Individual Character Poster',
    category: 'cinematic_poster',
    description: 'Pôster individual focado em um único personagem com arma/acessório característico.',
    bestFor: ['Apresentação de elenco', 'Personagens de franquia', 'Heróis e vilões'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'visual_reference', 'image_generator', 'virtual_tryon'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Medium 3/4 portrait of character', 'Distinct character color theme and motif in background', 'Intense character gaze'],
    promptAdditions: ['Blockbuster individual character poster, intense close-up portrait of protagonist with weapon, specialized color lighting signature, epic key art.'],
    negativePromptAdditions: ['multiple people, distorted facial anatomy'],
    tags: ['personagem', 'elenco', 'protagonista', 'vilao']
  },
  {
    code: '/ensembleposter',
    label: 'Ensemble Cast Floating Heads Poster',
    category: 'cinematic_poster',
    description: 'Composição clássica de blockbuster com múltiplos personagens em camadas de tamanho hierárquico.',
    bestFor: ['Vingadores/Star Wars style', 'Grandes elencos', 'Épicos de ficção'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Layered montage of character faces at varying scales', 'Main hero at center, villain looming in background, action vehicle at bottom', 'Rich dynamic composite'],
    promptAdditions: ['Epic ensemble cast movie poster, dynamic multi-character montage composition, villain silhouette looming above, battle fleet below, classic cinematic key art.'],
    negativePromptAdditions: ['isolated single person, disconnected bad cutouts'],
    tags: ['ensemble', 'elenco-completo', 'vingadores', 'montagem', 'epico']
  },
  {
    code: '/seriesposter',
    label: 'Streaming Series Key Art',
    category: 'cinematic_poster',
    description: 'Arte promocional para séries de TV e streaming (formato Netflix/HBO).',
    bestFor: ['Séries de streaming', 'Capas de episódios', 'Key art digital'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Atmospheric cinematic frame with narrative depth', 'Space on top for series logo', 'Binge-worthy premium drama feel'],
    promptAdditions: ['Premium streaming series key art poster, moody cinematic world-building, high production value character framing, HBO/Netflix prestige style.'],
    negativePromptAdditions: ['cheap soap opera look, bad studio lighting'],
    tags: ['serie', 'streaming', 'netflix', 'hbo', 'temporada']
  },
  {
    code: '/streamingcover',
    label: 'Streaming Tile Cover',
    category: 'cinematic_poster',
    description: 'Capa retangular (16:9) de catálogo para seleção em tela de TV ou app de streaming.',
    bestFor: ['Thumbnails de streaming', 'Card de filmes', 'Plataformas OTT'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Horizontal 16:9 cinematic frame', 'High contrast main character off-center', 'Room for title treatment on one side'],
    promptAdditions: ['Cinematic 16:9 streaming platform tile cover, horizontal dynamic frame, high visual contrast, immediate click appeal on TV interface.'],
    negativePromptAdditions: ['vertical format, boring centered passport photo'],
    tags: ['streaming-tile', '16-9', 'capa', 'ott', 'catalogo']
  },
  {
    code: '/keyart',
    label: 'Official Master Key Art',
    category: 'cinematic_poster',
    description: 'Arte-mãe de divulgação usada em outdoors, banners digitais e campanhas mundiais.',
    bestFor: ['Campanhas globais', 'Outdoors e mídias OOH', 'Divulgação oficial'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Hyper-polished compositing and lighting', 'Unmistakable franchise iconography', 'Museum-level visual polish'],
    promptAdditions: ['Master entertainment franchise key art, pinnacle commercial illustration and photographic composite, world-class lighting balance, unforgettable visual hook.'],
    negativePromptAdditions: ['amateur blending, rough cutout edges'],
    tags: ['key-art', 'mestre', 'oficial', 'outdoor', 'global']
  },
  {
    code: '/trailer-frame',
    label: 'Cinematic Trailer Frame Still',
    category: 'cinematic_poster',
    description: 'Frame congelado de trailer de cinema em 2.39:1 anamórfico com barras pretas de cinema.',
    bestFor: ['Frames de trailer', 'Teasers no YouTube', 'Stills de cinema'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Ultra-widescreen 2.39:1 letterbox aspect ratio', 'Film grain, chromatic aberration, anamorphic oval bokeh', 'High-tension dramatic action'],
    promptAdditions: ['Cinematic 2.39:1 widescreen movie trailer still, anamorphic lens rendering, subtle motion blur, master Hollywood color grading, intense dramatic moment.'],
    negativePromptAdditions: ['square 1:1, vertical 9:16, bright cartoon colors'],
    tags: ['trailer', 'widescreen', 'anamorfico', 'still', 'filme']
  },
  {
    code: '/cinematic-still',
    label: 'Photorealistic Film Still',
    category: 'cinematic_poster',
    description: 'Foto de cena de filme como se tivesse sido capturada com câmera ARRI Alexa e lentes Master Prime.',
    bestFor: ['Cenas de filme', 'Storyboards cinematográficos', 'Direção de arte'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['ARRI Alexa LF color rendition', 'Natural organic lighting roll-off', 'Hyper-realistic skin and set textures'],
    promptAdditions: ['Cinematographic still frame shot on ARRI Alexa with Master Prime lenses, natural organic lighting falloff, Kodak Vision3 500T film emulation, raw authenticity.'],
    negativePromptAdditions: ['AI glossy plastic look, digital oversaturation'],
    tags: ['arri-alexa', 'filme-still', 'kodak', 'cinema-real']
  },
  {
    code: '/epic-cinematic',
    label: 'Grand Scale Epic Scene',
    category: 'cinematic_poster',
    description: 'Cena de escala colossal: exércitos, paisagens alienígenas, explosões estelares ou monumentos gigantes.',
    bestFor: ['Fantasias épicas', 'Ficção científica grandiosa', 'Batalhas históricas'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vast epic horizon with colossal scale elements', 'Tiny human silhouette providing sense of scale', 'Atmospheric clouds, rays of God and dust'],
    promptAdditions: ['Epic grand scale cinematic landscape, colossal ancient structure towering into storm clouds, tiny explorer silhouetted in foreground, awe-inspiring god rays.'],
    negativePromptAdditions: ['cramped small room, flat horizon, boring sky'],
    tags: ['epico', 'gigante', 'escala', 'paisagem', 'monumental']
  }
];
