import { PresetDefinition } from '../types';

export const EDITING_PRESETS: PresetDefinition[] = [
  {
    code: '/aspectratio',
    label: 'Aspect Ratio Target Lock',
    category: 'editing_transform',
    description: 'Padronização estrita de proporção de tela (9:16 vertical, 16:9 widescreen, 1:1 quadrado ou 4:5 feed).',
    bestFor: ['Adaptação multiplataforma', 'Stories vs YouTube vs Feed', 'Enquadramento consistente'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Precise framing geometry', 'Content composed natively for target aspect ratio without cropping defects'],
    promptAdditions: ['Framed natively within specified aspect ratio bounds with balanced visual weight and edge margins.'],
    negativePromptAdditions: ['awkward pillarboxing, stretched proportions'],
    tags: ['proporcao', 'aspect-ratio', 'formato', '9-16', '16-9', '1-1']
  },
  {
    code: '/horizontal-to-vertical',
    label: 'Horizontal 16:9 to Vertical 9:16 Extension',
    category: 'editing_transform',
    description: 'Expansão inteligente de imagem horizontal para vertical preenchendo topo e base com continuidade coerente.',
    bestFor: ['Transformar filmes para TikTok/Reels', 'Adaptação de fotos horizontais para stories'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vertical 9:16 canvas with extended top sky/ceiling and extended bottom floor', 'Original subject centered seamlessly'],
    promptAdditions: ['Vertical 9:16 extension of original composition, seamless outpainting of top and bottom environment while preserving core subject fidelity.'],
    negativePromptAdditions: ['seam lines, mismatched lighting in extension, duplicated elements'],
    tags: ['horizontal-vertical', 'outpainting', 'extensao', 'stories-adaptacao']
  },
  {
    code: '/vertical-to-horizontal',
    label: 'Vertical 9:16 to Widescreen 16:9 Extension',
    category: 'editing_transform',
    description: 'Expansão lateral de imagem vertical para widescreen 16:9 preenchendo as laterais com cenário expansivo.',
    bestFor: ['Transformar posts em banners de site ou YouTube', 'Adaptação de retratos para cinema'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Expansive 16:9 widescreen horizon', 'Subject centered or rule-of-thirds', 'Natural environmental continuation on both sides'],
    promptAdditions: ['Widescreen 16:9 panoramic lateral expansion, natural outpainted background continuation on left and right sides with consistent depth.'],
    negativePromptAdditions: ['stretched borders, distorted side perspectives'],
    tags: ['vertical-horizontal', 'widescreen-adaptacao', 'panoramico', '16-9']
  },
  {
    code: '/backgroundchange',
    label: 'Smart Background Replacement',
    category: 'editing_transform',
    description: 'Substituição completa do cenário de fundo mantendo a pessoa/produto original com iluminação reajustada.',
    bestFor: ['Trocar quarto por praia/estúdio', 'Mudar ambiente de produto', 'Composições criativas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Original subject perfectly isolated', 'New background integrated with matching ambient light wrap and contact shadows', 'Natural edge transitions'],
    promptAdditions: ['Seamless background replacement, pristine subject edge blending, matched directional ambient lighting wrap and natural contact ground shadow.'],
    negativePromptAdditions: ['halo cutout line, harsh green screen edges, mismatched lighting angles'],
    tags: ['trocar-fundo', 'recorte', 'novo-cenario', 'background-change']
  },
  {
    code: '/colorgrading',
    label: 'Cinematic Color Grading & LUT',
    category: 'editing_transform',
    description: 'Harmonização de cor profissional com paleta específica (Kodak Gold, Cine Teal/Amber, Moody Green).',
    bestFor: ['Consistência de feed', 'Look cinematográfico', 'Padronização de campanha'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Unified color harmony', 'Smooth highlight roll-off and rich shadow tones', 'Distinct color temperature personality'],
    promptAdditions: ['Master cinematic color grading, rich tonal curves, Kodak film color science, cohesive color palette throughout shadows and highlights.'],
    negativePromptAdditions: ['garish oversaturated tints, digital color banding'],
    tags: ['color-grading', 'lut', 'paleta-de-cor', 'cinematografico', 'kodak']
  },
  {
    code: '/upscale-details',
    label: 'Ultra-HD Micro Texture Restoration',
    category: 'editing_transform',
    description: 'Aumento de nitidez e restauração de micro-texturas (fios de cabelo, poros, tecidos, reflexos).',
    bestFor: ['Impressão de grande formato', 'Catálogos 4K', 'Pôsteres de cinema'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Razor sharp micro-contrast', 'Pristine fabric weave and skin pores', 'Zero digital compression noise'],
    promptAdditions: ['Ultra high-definition micro-detail rendering, razor sharp fabric weave, individual hair strand clarity, crystalline specular highlights.'],
    negativePromptAdditions: ['crunchy oversharpened halo, AI plastic blur, jagged pixel lines'],
    tags: ['upscale', 'nitidez-extrema', 'micro-textura', '4k', 'alta-definicao']
  },
  {
    code: '/clean-cleanup',
    label: 'Clean Element Removal & Polish',
    category: 'editing_transform',
    description: 'Remoção de elementos distrativos do fundo (fios, manchas, lixeiras, pessoas indesejadas).',
    bestFor: ['Limpeza de fotos', 'Imagens de produto perfeitas', 'Fotos imobiliárias'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Distraction-free pristine background', 'Flawless inpainting over removed areas', 'Clean focal emphasis on hero subject'],
    promptAdditions: ['Clean aesthetic retouching, elimination of all background clutter, spotless surfaces, pure distraction-free focus on hero subject.'],
    negativePromptAdditions: ['smudged clone stamp artifacts, blurry patch marks'],
    tags: ['limpeza', 'remover-distracao', 'polimento', 'foco-limpo']
  },
  {
    code: '/relight-scene',
    label: 'Full Scene Relighting',
    category: 'editing_transform',
    description: 'Transformação da luz da cena (ex: transformar dia nublado em pôr do sol dourado ou noite iluminada).',
    bestFor: ['Mudar hora do dia', 'Aumentar dramaticidade', 'Ajustar atmosfera'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['New primary light direction and color temperature', 'Re-cast shadows matching new light vector', 'Accurate specular reflections'],
    promptAdditions: ['Complete scene relighting with warm directional golden hour illumination, realistic shadow angle recalculation, warm skin speculars.'],
    negativePromptAdditions: ['conflicting dual light sources, ungrounded shadows'],
    tags: ['reiluminacao', 'relight', 'mudar-luz', 'por-do-sol', 'atmosfera']
  }
];
