import { PresetDefinition } from '../types';

export const FASHION_PRESETS: PresetDefinition[] = [
  {
    code: '/try-on',
    label: 'Standard Virtual Try-On',
    category: 'tryon_fashion',
    description: 'Vestimenta precisa da peça no modelo preservando caimento, dobras e identidade física.',
    bestFor: ['Troca de look', 'Catálogo de moda', 'E-commerce de vestuário'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Natural drape and fabric physics on the model', 'Accurate neckline and sleeve alignment', 'True-to-life proportions'],
    promptAdditions: ['High fidelity virtual try-on fashion photograph, flawless fabric drape matching body contours, photorealistic texture and seam details.'],
    negativePromptAdditions: ['mismatched body size, flat 2D sticker look, warped patterns, distorted skin tone'],
    tags: ['provador', 'try-on', 'vestimenta', 'moda', 'caimento']
  },
  {
    code: '/storyboard-tryon',
    label: 'Storyboard Try-On Narrative',
    category: 'tryon_fashion',
    description: 'Sequência de 4 ou 5 takes com travas de identidade e visualização 360 do look.',
    bestFor: ['Campanhas de moda', 'Carrosséis de vestuário', 'Vídeos de provador virtual'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Consistent model identity across all angles', 'Front, 3/4, side and detail takes', 'Cohesive lighting setup'],
    defaultTakes: 5,
    promptAdditions: ['Cohesive 5-take try-on storyboard with strict person identity lock, exact garment fidelity, and progressive camera angles.'],
    negativePromptAdditions: ['changing face identity between takes, mismatched clothing color between shots'],
    tags: ['storyboard', 'multi-take', 'sequencia', 'campanha-moda'],
    suggestedCampaignType: 'storyboard_visual'
  },
  {
    code: '/fashion-carousel',
    label: 'Fashion Lookbook Carousel',
    category: 'tryon_fashion',
    description: 'Carrossel dinâmico combinando looks completos, poses editoriais e close em detalhes.',
    bestFor: ['Instagram Fashion Carousel', 'Lookbook de coleção', 'Shein/Zara style'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['carousel', 'storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Editorial poses', 'Clean architectural or studio background', 'Detailed fabric close-up card'],
    promptAdditions: ['Fashion lookbook carousel series, clean editorial poses, high-fashion styling, cohesive light palette.'],
    negativePromptAdditions: ['stiff amateur poses, low detail fabrics'],
    tags: ['carrossel-moda', 'lookbook', 'colecao', 'editorial'],
    suggestedCampaignType: 'fashion_carousel'
  },
  {
    code: '/editorial-premium',
    label: 'Premium High-Fashion Editorial',
    category: 'tryon_fashion',
    description: 'Estética Vogue/Harper’s Bazaar com iluminação escultural e poses sofisticadas.',
    bestFor: ['Marcas de luxo', 'Alta costura', 'Campanhas conceituais'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sculptural Chiaroscuro studio lighting', 'Vogue editorial framing and attitude', 'Subtle film grain and luxury color grade'],
    promptAdditions: ['Vogue haute-couture editorial fashion shoot, dramatic sculptural lighting, haute elegance, flawless tailoring texture, master magazine aesthetic.'],
    negativePromptAdditions: ['cheap lighting, basic stock photo, generic smile, plastic skin'],
    tags: ['editorial', 'vogue', 'luxo', 'alta-costura'],
    suggestedCampaignType: 'editorial_premium'
  },
  {
    code: '/lookbook',
    label: 'Clean Studio Lookbook',
    category: 'tryon_fashion',
    description: 'Catálogo de estúdio limpo com modelo em fundo neutro e iluminação suave.',
    bestFor: ['E-commerce fashion', 'Lojas virtuais', 'Guia de caimento'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'carousel'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Full-body standing shot', 'Soft neutral light gray or beige cyclorama', 'Natural relaxed fashion stance'],
    promptAdditions: ['Clean commercial fashion lookbook, full body shot, soft diffuse cyclorama lighting, natural upright posture, true fabric color representation.'],
    negativePromptAdditions: ['extreme shadows, cropped head, distorted feet'],
    tags: ['lookbook', 'catalogo', 'full-body', 'neutro']
  },
  {
    code: '/studio-fashion',
    label: 'Studio Fashion Flash',
    category: 'tryon_fashion',
    description: 'Estética flash de estúdio com alto contraste, cores vibrantes e pegada anos 90.',
    bestFor: ['Streetwear', 'Campanhas jovens', 'Moda urbana'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Direct on-camera flash with crisp edge shadow', 'Punchy saturated colors', 'Dynamic bold attitude'],
    promptAdditions: ['Direct flash studio fashion photography, 90s high-energy magazine look, crisp shadows, bold streetwear styling.'],
    negativePromptAdditions: ['soft washed out look, boring posture'],
    tags: ['flash', 'streetwear', 'anos-90', 'urbano']
  },
  {
    code: '/lifestyle-fashion',
    label: 'Street Style & Lifestyle Fashion',
    category: 'tryon_fashion',
    description: 'Modelo caminhando em cenário urbano autêntico (rua de Paris, NY, Milão).',
    bestFor: ['Street style', 'Moda casual chic', 'Outfits de rua'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Urban street background with elegant architectural bokeh', 'In-motion walking stride', 'Golden hour sunlight'],
    promptAdditions: ['Street style fashion photography in a chic European city, model walking naturally, golden hour backlighting, beautiful natural movement.'],
    negativePromptAdditions: ['crowded messy street with distracting signs, distorted legs'],
    tags: ['street-style', 'rua', 'movimento', 'urbano']
  },
  {
    code: '/accessory-focus',
    label: 'Accessory & Jewelry Focus',
    category: 'tryon_fashion',
    description: 'Foco exclusivo em bolsas, joias, cintos e acessórios vestidos no corpo.',
    bestFor: ['Bolsas de mão', 'Joias e colares', 'Lenços e cintos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Tight medium crop on torso or hands', 'Razor sharp focus on hardware and metal finish', 'Complementary neutral clothing'],
    promptAdditions: ['Fashion accessory showcase, tight crop on model holding luxury bag, razor-sharp hardware reflection, soft luxurious fabric context.'],
    negativePromptAdditions: ['blurry buckles, distorted chain links, pixelated stones'],
    tags: ['acessorio', 'bolsa', 'joia', 'cinto']
  },
  {
    code: '/clothing-tryon',
    label: 'Full Garment Try-On Lock',
    category: 'tryon_fashion',
    description: 'Trava estrita em vestidos, camisas, casacos e calças com preservação do molde.',
    bestFor: ['Roupas completas', 'Vestidos de festa', 'Camisaria'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Complete garment visibility from collar to hem', 'Exact pattern and color replication', 'Natural drape at waist and shoulders'],
    promptAdditions: ['Accurate garment fitting on model with full structural preservation of collar, sleeve length, fabric pattern, and hemline.'],
    negativePromptAdditions: ['altered pattern, modified collar style, missing buttons'],
    tags: ['roupa', 'vestido', 'camisa', 'caimento']
  },
  {
    code: '/sunglasses-tryon',
    label: 'Eyewear & Sunglasses Try-On',
    category: 'tryon_fashion',
    description: 'Encaixe anatômico perfeito de óculos escuros e armações no rosto da pessoa.',
    bestFor: ['Óculos de sol', 'Armações de grau', 'Acessórios faciais'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Close portrait crop on face', 'Realistic lens tint and gentle reflection', 'Precise nose bridge and ear temple placement'],
    promptAdditions: ['Eyewear try-on portrait, luxury sunglasses resting naturally on nose bridge, realistic gradient tint lens reflections, sharp frame acetate detail.'],
    negativePromptAdditions: ['floating sunglasses, asymmetrical crooked frame, obscured eyes if transparent lens'],
    tags: ['oculos', 'sunglasses', 'rosto', 'armacao']
  },
  {
    code: '/watch-tryon',
    label: 'Luxury Watch On Wrist',
    category: 'tryon_fashion',
    description: 'Relógio encaixado perfeitamente no pulso com detalhes de mostrador e pulseira.',
    bestFor: ['Relógios de pulso', 'Smartwatches', 'Pulseiras masculinas e femininas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Wrist and hand perspective', 'Sapphire crystal reflection', 'Detailed bezel and dial hour markers'],
    promptAdditions: ['Luxury watch fitted onto wrist, detailed dial chronographs, brushed bezel finish, elegant sleeve cuff context.'],
    negativePromptAdditions: ['distorted clock hands, unreadable watch face, oversized strap'],
    tags: ['relogio', 'pulso', 'luxo', 'mostrador']
  },
  {
    code: '/jewelry-tryon',
    label: 'Jewelry & Gemstone Try-On',
    category: 'tryon_fashion',
    description: 'Colares, brincos e anéis vestidos com brilho de pedras preciosas e reflexo nobre.',
    bestFor: ['Colares e gargantilhas', 'Brincos', 'Anéis e alianças'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Soft glowing skin tones', 'Sparkling faceted gemstone speculars', 'Delicate metal chain links'],
    promptAdditions: ['Fine jewelry try-on, necklace resting gracefully on collarbone, brilliant diamond reflections, soft flattering skin tones.'],
    negativePromptAdditions: ['dull cloudy stones, fused blobs instead of chain, pixelated metal'],
    tags: ['joia', 'colar', 'brinco', 'anel', 'diamante']
  },
  {
    code: '/bag-tryon',
    label: 'Handbag & Tote Try-On',
    category: 'tryon_fashion',
    description: 'Bolsa posicionada no ombro, na mão ou na transversal de forma natural.',
    bestFor: ['Bolsas de couro', 'Mochilas', 'Clutches'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Model holding or wearing bag naturally', 'Accurate scale relative to body', 'Detailed leather grain and metal hardware'],
    promptAdditions: ['Fashion model wearing designer handbag, correct anatomical scale and strap tension, rich leather grain, chic outfit pairing.'],
    negativePromptAdditions: ['bag passing through body, floating strap, distorted logos'],
    tags: ['bolsa', 'handbag', 'couro', 'escala']
  },
  {
    code: '/shoe-tryon',
    label: 'Footwear & Sneaker Try-On',
    category: 'tryon_fashion',
    description: 'Tênis e sapatos vestidos nos pés com perspectiva dinâmica e caimento com a calça.',
    bestFor: ['Sneakers', 'Saltos altos', 'Botas', 'Chinelos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Low-angle foot/ankle crop', 'Lace and sole texture details', 'Natural floor contact and movement crease'],
    promptAdditions: ['Footwear try-on shot, sneaker worn on foot interacting naturally with ground, clean pant cuff break, crisp sole and stitching details.'],
    negativePromptAdditions: ['distorted toes, rubber blob shoes, mismatched foot sizes'],
    tags: ['calcado', 'sneaker', 'tenis', 'sapato', 'pe']
  },
  {
    code: '/mirror-look',
    label: 'Mirror Selfie Outfit Check',
    category: 'tryon_fashion',
    description: 'Foto no espelho (OOTD) espontânea mostrando o look completo.',
    bestFor: ['Stories do Instagram', 'OOTD (Outfit of the Day)', 'Provas de roupa rápidas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Phone covering part of chest/face or held beside', 'Full body reflection in clean modern mirror', 'Warm ambient room light'],
    promptAdditions: ['OOTD mirror selfie full-body outfit check, natural bedroom mirror reflection, stylish smartphone grip, trendy casual styling.'],
    negativePromptAdditions: ['dirty smudged mirror, warped reflection, extra limbs'],
    tags: ['espelho', 'mirror-selfie', 'ootd', 'look-do-dia']
  }
];
