import { PresetDefinition } from '../types';

export const LIGHTING_PRESETS: PresetDefinition[] = [
  {
    code: '/cinematic',
    label: 'Cinematic Master Lighting',
    category: 'lighting_mood',
    description: 'Iluminação de cinema com alto contraste, luz principal suave, luz de preenchimento e luz de recorte.',
    bestFor: ['Cinema', 'Retratos dramáticos', 'Pôsteres'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'visual_reference', 'image_generator', 'virtual_tryon'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Chiaroscuro shadow falloff', 'Warm tungsten key with cool cyan fill', 'Subtle atmospheric haze'],
    promptAdditions: ['Cinematic master lighting setup, rich tonal contrast with soft shadow gradients, subtle atmospheric haze, filmic aesthetic.'],
    negativePromptAdditions: ['flat overhead office lighting, flash glare, blown out highlights'],
    tags: ['cinematografico', 'luz-cinema', 'chiaroscuro', 'contraste']
  },
  {
    code: '/studio-lighting',
    label: 'Professional Studio Softbox',
    category: 'lighting_mood',
    description: 'Iluminação com grandes octaboxes proporcionando sombras aveludadas e reflexos circulares nos olhos.',
    bestFor: ['E-commerce', 'Moda', 'Retratos corporativos'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Giant diffuse octabox light source', 'Flattering catchlights in pupils', 'Velvety smooth skin tone gradients'],
    promptAdditions: ['Commercial studio softbox lighting, large diffused octabox key, flattering round catchlights in eyes, velvety shadow roll-off.'],
    negativePromptAdditions: ['harsh direct sun, speckled light'],
    tags: ['estudio', 'softbox', 'octabox', 'suave']
  },
  {
    code: '/soft-light',
    label: 'Ultra-Soft Diffuse Daylight',
    category: 'lighting_mood',
    description: 'Luz natural extremamente suave simulando dia nublado ou janela com cortina de linho.',
    bestFor: ['Skincare', 'Produtos naturais', 'Moda minimalista'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Shadowless soft wrap-around daylight', 'Delicate organic skin tones', 'Peaceful calm atmosphere'],
    promptAdditions: ['Ultra-soft diffuse daylight, overcast morning window illumination, seamless shadow-free skin rendition, serene mood.'],
    negativePromptAdditions: ['hard dark shadows, high contrast neon'],
    tags: ['luz-suave', 'dia-nublado', 'difusa', 'natural']
  },
  {
    code: '/hard-light',
    label: 'Hard Direct Sunlight & Crisp Shadows',
    category: 'lighting_mood',
    description: 'Luz dura com sombras pretas e recortadas, estilo editorial de verão e meio-dia.',
    bestFor: ['Óculos de sol', 'Moda praia', 'Arquitetura moderna'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Crisp geometric cast shadows', 'High specular glints on water and metal', 'Sun-drenched summer warmth'],
    promptAdditions: ['Hard directional direct sunlight, razor-sharp architectural cast shadows, high-contrast summer editorial mood.'],
    negativePromptAdditions: ['soft blurred shadows, cloudy grey sky'],
    tags: ['luz-dura', 'sol-direto', 'sombra-marcada', 'verao']
  },
  {
    code: '/rim-light',
    label: 'Edge Rim Lighting & Silhouette Separation',
    category: 'lighting_mood',
    description: 'Luz de contra intensa desenhando a linha do corpo ou produto e separando do fundo escuro.',
    bestFor: ['Atletas e fitness', 'Garrafas e eletrônicos', 'Pôsteres de ação'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Luminous silhouette halo edge', 'Subject separated sharply from dark backdrop', 'Sculpted muscle/product contours'],
    promptAdditions: ['Dramatic edge rim lighting (kicker light), brilliant glowing outline defining subject silhouette against dark background.'],
    negativePromptAdditions: ['flat frontal flash, washed out background'],
    tags: ['rim-light', 'luz-de-borda', 'silhueta', 'recorte']
  },
  {
    code: '/backlit',
    label: 'Golden Hour Backlit Glow',
    category: 'lighting_mood',
    description: 'Sol dourado atrás do sujeito criando halo nos cabelos e atmosfera poética.',
    bestFor: ['Ensaios ao ar livre', 'Moda boho', 'Perfumes e pôr do sol'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Warm golden backlighting', 'Sun flare kissing the lens edge', 'Hair strand illumination'],
    promptAdditions: ['Golden hour backlit photography, warm sunset glowing behind subject, luminous hair rim light, dreamy atmospheric flare.'],
    negativePromptAdditions: ['cold dark studio, flash in face'],
    tags: ['contra-luz', 'golden-hour', 'halo', 'cabelo']
  },
  {
    code: '/moody-lighting',
    label: 'Moody Dark Atmospheric Tone',
    category: 'lighting_mood',
    description: 'Ambiente soturno e reflexivo com sombras profundas e pontos seletivos de luz.',
    bestFor: ['Whisky e tabaco', 'Cafeterias vintage', 'Dramas intensos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Predominantly low-key dark environment', 'Single warm pool of light', 'Rich moody wood and leather tones'],
    promptAdditions: ['Moody low-key atmospheric lighting, selective warm pool of illumination in darkened vintage room, introspective vibe.'],
    negativePromptAdditions: ['bright cheerful white room, clinical fluorescent light'],
    tags: ['moody', 'soturno', 'intimista', 'baixo-tom']
  },
  {
    code: '/dramatic-lighting',
    label: 'Caravaggio Dramatic Chiaroscuro',
    category: 'lighting_mood',
    description: 'Contraste extremo entre luz e escuridão com estética de pintura renascentista.',
    bestFor: ['Alta costura', 'Key art de luxo', 'Retratos de alta intensidade'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Pure black shadows meeting intense directional key light', 'Renaissance painting drama', 'Sculptural facial structure'],
    promptAdditions: ['Dramatic Caravaggio chiaroscuro lighting, intense directional spotlight slicing through deep obsidian shadows, sculptural drama.'],
    negativePromptAdditions: ['flat daylight, pastel tones'],
    tags: ['dramatico', 'chiaroscuro', 'caravaggio', 'contraste-extremo']
  },
  {
    code: '/natural-light',
    label: 'Organic Window Sunlight',
    category: 'lighting_mood',
    description: 'Luz orgânica de janela entrando em um quarto com sombras naturais de plantas ou persianas.',
    bestFor: ['Lifestyle de casa', 'Café da manhã', 'Skincare matinal'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Warm directional sunlight beam', 'Botanical leaf or lace shadow cast', 'Clean cozy home atmosphere'],
    promptAdditions: ['Pure organic morning window sunlight, delicate botanical leaf shadows dancing on floor, warm comforting natural glow.'],
    negativePromptAdditions: ['artificial LED rings, cold studio backdrop'],
    tags: ['luz-natural', 'janela', 'manha', 'aconchego']
  },
  {
    code: '/volumetric-light',
    label: 'God Rays & Volumetric Light Beams',
    category: 'lighting_mood',
    description: 'Feixes de luz visíveis atravessando poeira no ar, névoa ou janelas de catedrais.',
    bestFor: ['Cenas épicas', 'Templos e florestas', 'Perfumes místicos'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Distinct visible rays of light slicing through air', 'Airborne dust/smoke particles catching illumination', 'Sacred epic majesty'],
    promptAdditions: ['Volumetric god rays slicing through atmospheric haze and mist, tangible light beams, breathtaking majestic atmosphere.'],
    negativePromptAdditions: ['flat clear air with no beam visibility'],
    tags: ['raios-de-deus', 'feixes', 'volumetrico', 'nevoa', 'mistico']
  },
  {
    code: '/depth-of-field',
    label: 'Shallow Depth of Field (f/1.2 Bokeh)',
    category: 'lighting_mood',
    description: 'Profundidade de campo rasa (f/1.2) isolando o sujeito com fundo cremoso.',
    bestFor: ['Retratos', 'Produtos em mãos', 'Foco exclusivo'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Ultra-wide f/1.2 aperture rendering', 'Razor sharp subject eyes/edges', 'Creamy melted background'],
    promptAdditions: ['Ultra shallow depth of field shot at f/1.2, subject sharply isolated with breathtaking creamy optical background blur.'],
    negativePromptAdditions: ['deep focus with sharp background objects distracting'],
    tags: ['f-1-2', 'profundidade-campo', 'bokeh', 'desfocado']
  },
  {
    code: '/bokeh',
    label: 'Dreamy Optical Bokeh Balls',
    category: 'lighting_mood',
    description: 'Círculos luminosos de luzes da cidade ou pisca-pisca brilhando suavemente no fundo.',
    bestFor: ['Noites urbanas', 'Datas festivas', 'Comerciais natalinos e de joias'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Luminous circular or hexagonal bokeh balls in background', 'Warm festive or city night lights', 'Magical soft vibe'],
    promptAdditions: ['Dreamy round optical bokeh lights in background, glittering festive city lights out of focus, magical enchanting aesthetic.'],
    negativePromptAdditions: ['plain dark backdrop, flat gray blur'],
    tags: ['bokeh', 'luzes-fundo', 'magico', 'noite-urbana']
  },
  {
    code: '/motion-blur',
    label: 'Cinematic Motion Blur Panning',
    category: 'lighting_mood',
    description: 'Sujeito nítido enquanto o fundo e as luzes passam borrados pela velocidade.',
    bestFor: ['Carros em alta velocidade', 'Corredores e esportes', 'Pessoas no metrô'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sharp tracking subject', 'Horizontal speed blur streaks across background', 'Sense of extreme velocity'],
    promptAdditions: ['Cinematic motion blur panning shot, razor-sharp tracked subject with vibrant horizontal motion streaks in background, dynamic speed.'],
    negativePromptAdditions: ['entire image blurry including subject, static boring scene'],
    tags: ['motion-blur', 'velocidade', 'movimento', 'panning']
  },
  {
    code: '/freeze-frame',
    label: 'High-Shutter Freeze Frame',
    category: 'lighting_mood',
    description: 'Velocidade de obturador 1/8000s congelando respingos, saltos no ar e poeira com nitidez extrema.',
    bestFor: ['Tênis esportivos', 'Bebidas caindo no copo', 'Pós coloridos'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Zero motion blur', 'Individual suspended liquid droplets and micro-particles', 'High-energy kinetic freeze'],
    promptAdditions: ['1/8000s high-speed shutter freeze frame, liquid splash suspended crisp mid-air with zero motion blur, immaculate clarity.'],
    negativePromptAdditions: ['motion smear, blurry edges'],
    tags: ['freeze-frame', 'congelamento', '1-8000s', 'nitidez-extrema']
  },
  {
    code: '/reflection',
    label: 'Mirror & Water Surface Reflection',
    category: 'lighting_mood',
    description: 'Reflexo límpido em poça de água, tampo de vidro preto ou espelho polido.',
    bestFor: ['Carros', 'Perfumes de luxo', 'Cidades noturnas'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Pristine glossy mirror reflection on ground plane', 'Symmetrical inverted world reflection', 'Glass or wet lacquer finish'],
    promptAdditions: ['Flawless glossy surface reflection, crisp mirrored image on wet black marble floor, opulent symmetry.'],
    negativePromptAdditions: ['turbid dirty water, broken distorted reflection'],
    tags: ['reflexo', 'espelho', 'superficie-molhada', 'vidro']
  },
  {
    code: '/shadow-play',
    label: 'Artistic Shadow Play & Gobo Patterns',
    category: 'lighting_mood',
    description: 'Sombras projetadas de folhas tropicais, janelas mouriscas ou persianas geométricas.',
    bestFor: ['Moda conceitual', 'Skincare', 'Editoriais artísticos'],
    compatibleModules: ['creative_director', 'virtual_tryon', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Intricate gobo shadow patterns cast across subject face/body', 'High contrast geometric shapes', 'Arthouse visual poetry'],
    promptAdditions: ['Artistic gobo shadow play, palm frond and architectural lattice shadows cast across model face and collarbone, poetic contrast.'],
    negativePromptAdditions: ['flat untextured lighting'],
    tags: ['gobo', 'sombras-artisticas', 'persiana', 'folhagem']
  }
];
