import { PresetDefinition } from '../types';

export const PRODUCT_PRESETS: PresetDefinition[] = [
  {
    code: '/productshot',
    label: 'Standard Product Shot',
    category: 'product_packshot',
    description: 'Fotografia comercial padrão com iluminação de estúdio equilibrada.',
    bestFor: ['E-commerce', 'Catálogo de produtos', 'Listagens de marketplace'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Studio softbox lighting', 'Sharp edges and accurate color balance', 'Clean neutral gradient backdrop'],
    promptAdditions: ['Commercial studio product photography, clean softbox key light, subtle fill, razor-sharp focus, true colors.'],
    negativePromptAdditions: ['harsh glare, dirty backdrop, clipped highlights, chromatic aberration'],
    tags: ['produto', 'estudio', 'catalogo', 'comercial']
  },
  {
    code: '/studioshot',
    label: 'Studio Master Lighting',
    category: 'product_packshot',
    description: 'Iluminação de estúdio profissional com 3 pontos de luz e gradiente suave.',
    bestFor: ['Produtos premium', 'Publicidade impressa e digital', 'Hero banners'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Three-point lighting setup', 'Rim light separating subject from background', 'Smooth studio cyclorama gradient'],
    promptAdditions: ['High-end studio product shoot, precision three-point lighting, distinct rim light edge definition, infinite cyc studio.'],
    negativePromptAdditions: ['flat lighting, harsh uncontrolled reflections, dusty lens'],
    tags: ['estudio', 'iluminacao', '3-pontos', 'profissional']
  },
  {
    code: '/packshot',
    label: 'Packaging & Packshot',
    category: 'product_packshot',
    description: 'Enquadramento focado na embalagem, caixa e frasco com legibilidade máxima.',
    bestFor: ['Cosméticos', 'Suplementos', 'Alimentos e bebidas', 'Eletrônicos na caixa'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Frontal and 3/4 packaging angle', 'Crisp typography on labels', 'Shadow beneath packaging grounding the object'],
    promptAdditions: ['Commercial packshot photography, clean product packaging centered, crisp readable label details, soft cast shadow.'],
    negativePromptAdditions: ['distorted label text, unreadable packaging, dented box'],
    tags: ['packshot', 'embalagem', 'rotulo', 'caixa']
  },
  {
    code: '/heroshot',
    label: 'Hero Product Shot',
    category: 'product_packshot',
    description: 'Enquadramento dramático em ângulo ligeiramente baixo transmitindo imponência.',
    bestFor: ['Lançamentos de produto', 'Páginas de vendas (Hero section)', 'Campanhas de destaque'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Slight low angle hero perspective', 'Dramatic volumetric or directional lighting', 'Commanding central presence'],
    promptAdditions: ['Hero product shot, low-angle perspective conveying grandeur and premium stature, cinematic rim lighting, commanding presence.'],
    negativePromptAdditions: ['weak composition, tilted horizon, flat lighting'],
    tags: ['hero', 'destaque', 'hero-shot', 'impacto']
  },
  {
    code: '/macro-detail',
    label: 'Macro Detail Focus',
    category: 'product_packshot',
    description: 'Lente macro com aproximação extrema em texturas, costuras, engrenagens e materiais.',
    bestFor: ['Relógios de luxo', 'Joias', 'Texturas de tecidos e couros', 'Maquiagem'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Ultra shallow depth of field', 'Microscopic texture fidelity', 'Precision optical highlights'],
    promptAdditions: ['Extreme macro product photography, 100mm macro lens, ultra shallow depth of field, tactile surface texture, micro craftsmanship.'],
    negativePromptAdditions: ['blurry subject, digital noise, muddy textures'],
    tags: ['macro', 'detalhe', 'textura', 'aproximacao']
  },
  {
    code: '/close-up-detail',
    label: 'Close-Up Detail Shot',
    category: 'product_packshot',
    description: 'Plano fechado ressaltando características exclusivas do produto.',
    bestFor: ['Botões e fechos', 'Bordados e estampas', 'Conectores e portas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Close-up framing 50-85mm', 'Crisp subject focus with smooth background falloff', 'Accurate material reflection'],
    promptAdditions: ['Crisp close-up product detail shot, tight framing focusing on build craftsmanship, soft bokeh background.'],
    negativePromptAdditions: ['out of focus detail, blurry edges'],
    tags: ['close-up', 'detalhe', 'plano-fechado']
  },
  {
    code: '/flatlay',
    label: 'Flatlay Composition',
    category: 'product_packshot',
    description: 'Disposição organizada vista de cima com elementos complementares estéticos.',
    bestFor: ['Moda e outfits', 'Itens de mesa e escritório', 'Kits de cosméticos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['90-degree direct top-down view', 'Geometric knolling layout', 'Even soft lighting across all objects'],
    promptAdditions: ['Curated flatlay photography from directly above (knolling arrangement), perfectly organized items, even diffuse lighting.'],
    negativePromptAdditions: ['tilted top view, messy clutter, harsh one-sided shadow'],
    tags: ['flatlay', 'knolling', 'organizacao', 'top-down']
  },
  {
    code: '/top-down',
    label: 'Top-Down Bird Eye View',
    category: 'product_packshot',
    description: 'Visão zenital direta (vista aérea) com enquadramento geométrico limpo.',
    bestFor: ['Pratos e culinária', 'Mesas de trabalho', 'Kits de ferramentas'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Strict overhead 90-degree angle', 'Balanced symmetrical composition', 'Clean tabletop surface'],
    promptAdditions: ['Direct overhead top-down bird-eye photography, geometric balance, pristine surface texture.'],
    negativePromptAdditions: ['angled perspective, distortion at edges'],
    tags: ['zenital', 'top-down', 'aereo', 'mesa']
  },
  {
    code: '/white-background',
    label: 'Pure White Background E-commerce',
    category: 'product_packshot',
    description: 'Fundo branco 100% puro para marketplaces com sombra de contato natural.',
    bestFor: ['Mercado Livre', 'Amazon', 'Catálogos limpos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['RGB 255/255/255 pure white backdrop', 'Realistic ground contact shadow', 'No color spill on subject'],
    promptAdditions: ['Product shot on pure seamless solid white background, isolated clean commercial look, realistic grounding contact shadow.'],
    negativePromptAdditions: ['gray tint background, floating object without shadow, halo outline around edges'],
    tags: ['fundo-branco', 'ecommerce', 'isolado', 'catalogo']
  },
  {
    code: '/black-background',
    label: 'Black Luxury Background',
    category: 'product_packshot',
    description: 'Fundo preto profundo com iluminação de borda e reflexo espelhado sutil.',
    bestFor: ['Perfumes', 'Bebidas premium', 'Eletrônicos escuros', 'Joias de ouro'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Deep obsidian black background', 'Sharp rim light highlighting silhouette', 'Subtle mirror reflection on floor'],
    promptAdditions: ['Luxury product photography on deep black background, dramatic edge rim lighting, subtle glossy reflection on surface below.'],
    negativePromptAdditions: ['washed out blacks, gray noise, blown out highlights'],
    tags: ['fundo-preto', 'luxo', 'dramatico', 'perfume']
  },
  {
    code: '/minimal-product',
    label: 'Minimalist Podiums & Geometry',
    category: 'product_packshot',
    description: 'Composição minimalista com pódios geométricos, sombras suaves e estética nórdica.',
    bestFor: ['Skincare', 'Decoração', 'Marcas minimalistas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Geometric pedestals (cylinders/cubes)', 'Muted neutral pastel or earth tones', 'Artistic directional sunlight shadows'],
    promptAdditions: ['Minimalist aesthetic product photography on architectural podiums, muted earth tones, delicate sunlight shadows, clean modern elegance.'],
    negativePromptAdditions: ['cluttered scene, loud saturated neon colors, kitsch props'],
    tags: ['minimalista', 'podio', 'estetica', 'skincare']
  },
  {
    code: '/premium-product-shot',
    label: 'Premium Commercial Shot',
    category: 'product_packshot',
    description: 'Produção comercial de alto valor com textura rica e reflexos calibrados.',
    bestFor: ['Campanhas institucionais', 'Publicidade global', 'Anúncios de luxo'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Master advertising studio look', 'Subtle atmospheric haze or micro-droplets', 'Perfect gradient speculars on glass and metal'],
    promptAdditions: ['Award-winning commercial product photography, impeccable lighting craftsmanship, rich material texture, pristine atmospheric clarity.'],
    negativePromptAdditions: ['cheap amateur lighting, plastic look, low detail'],
    tags: ['premium', 'publicidade', 'comercial', 'alto-padrao']
  },
  {
    code: '/texture-focus',
    label: 'Texture & Formula Focus',
    category: 'product_packshot',
    description: 'Foco na textura física: cremes em espátula, gotas d’água, tecido tátil e grãos.',
    bestFor: ['Cremes e séruns', 'Comidas e café', 'Couros e tecidos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sensory macro focus', 'Crisp droplet reflections or creamy swirls', 'Warm tactile raking light'],
    promptAdditions: ['Sensory product photography focusing on rich cream texture swatch and water droplets, side raking light emphasizing depth and viscosity.'],
    negativePromptAdditions: ['flat blur, artificial plastic look, dry surface'],
    tags: ['textura', 'formula', 'gota', 'sensorial']
  },
  {
    code: '/material-focus',
    label: 'Material & Craftsmanship',
    category: 'product_packshot',
    description: 'Destaque para matéria-prima nobre: aço escovado, madeira maciça, couro legítimo.',
    bestFor: ['Móveis', 'Acessórios de couro', 'Hardware e relógios'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Natural wood/stone textures', 'Anisotropic metal highlights', 'Handcrafted authenticity'],
    promptAdditions: ['Craftsmanship-focused product photo highlighting authentic raw materials, brushed metal grain, genuine leather stitching, organic textures.'],
    negativePromptAdditions: ['fake plastic sheen, pixelated grain, poor craftsmanship'],
    tags: ['material', 'artesanal', 'couro', 'metal']
  },
  {
    code: '/360-product',
    label: '360° Clean Turntable View',
    category: 'product_packshot',
    description: 'Enquadramento pronto para visualização giratória 360 graus com iluminação uniforme.',
    bestFor: ['Sapatos', 'Bolsas', 'Equipamentos', 'Visualizadores 3D'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Isometric or 3/4 turn angle', 'Omnidirectional even softbox light', 'Fixed axis centering'],
    promptAdditions: ['Clean 3/4 turntable product perspective, even multi-directional studio lighting, seamless ground shadow, calibrated centering.'],
    negativePromptAdditions: ['asymmetrical harsh shadows, shifted center axis'],
    tags: ['360', 'giratorio', 'isometria', 'calcado']
  }
];
