import { PresetDefinition } from '../types';

export const SOCIAL_PRESETS: PresetDefinition[] = [
  {
    code: '/youtube-thumbnail',
    label: 'YouTube High-CTR Thumbnail',
    category: 'social_thumbnail',
    description: 'Capa de YouTube com alta taxa de clique: expressão facial exagerada, recorte nítido e alto contraste.',
    bestFor: ['Thumbnails de YouTube', 'Canais de curiosidades', 'Reviews de tecnologia', 'Vlogs'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['16:9 horizontal layout', 'Subject on right or left with bright rim outline', 'Vibrant saturated background with clean text zone'],
    promptAdditions: ['High CTR YouTube thumbnail design, 16:9 aspect ratio, expressive human subject with intense facial emotion, bright neon rim glow, clean readable negative space on left.'],
    negativePromptAdditions: ['dull colors, low contrast, tiny unreadable elements in center, cluttered mess'],
    tags: ['youtube', 'thumbnail', 'ctr', 'capa', '16-9']
  },
  {
    code: '/reels-cover',
    label: 'Instagram Reels Cover',
    category: 'social_thumbnail',
    description: 'Capa vertical 9:16 com área segura central 1:1 para feed do Instagram.',
    bestFor: ['Reels', 'Capas de vídeo verticais', 'Feed organizado'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vertical 9:16 frame', 'Main subject and title contained strictly within center 1:1 safe zone', 'Aesthetic color palette'],
    promptAdditions: ['Instagram Reels vertical 9:16 cover photo, key subject centered inside square 1:1 feed safe zone, aesthetic modern color harmony, bold stopping power.'],
    negativePromptAdditions: ['important elements cut off at edges, blurry text'],
    tags: ['reels', 'instagram', 'capa-vertical', 'safe-zone', 'feed']
  },
  {
    code: '/tiktok-cover',
    label: 'TikTok Viral Cover Tile',
    category: 'social_thumbnail',
    description: 'Capa de perfil do TikTok com gancho visual instantâneo e visual limpo.',
    bestFor: ['TikTok perfil', 'Organização de playlists', 'Vídeos em série'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vertical 9:16 ratio', 'High curiosity element centered', 'Clear space on bottom for TikTok interface'],
    promptAdditions: ['Viral TikTok video cover frame, punchy colors, maximum visual intrigue, optimized for vertical mobile display grid.'],
    negativePromptAdditions: ['dark boring frame, crowded bottom edge'],
    tags: ['tiktok', 'capa-tiktok', 'viral', 'mobile']
  },
  {
    code: '/story-cover',
    label: 'Instagram Story & Destaque Cover',
    category: 'social_thumbnail',
    description: 'Arte vertical 9:16 para stories diários, enquetes e capas de destaques.',
    bestFor: ['Stories do Instagram', 'Capas de destaque', 'Enquetes e caixinhas'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vertical 9:16 layout', 'Clean minimalist center icon or photo', 'Margin for story header and reply bar'],
    promptAdditions: ['Instagram story vertical design, clean aesthetic center focal point, ample top and bottom breathing room for native UI widgets.'],
    negativePromptAdditions: ['edge clutter, overlapping with UI bars'],
    tags: ['story', 'destaque', 'instagram-stories', 'vertical']
  },
  {
    code: '/carousel-cover',
    label: 'Carousel First Slide Hook',
    category: 'social_thumbnail',
    description: 'Primeiro card de carrossel desenhado exclusivamente para fazer o usuário deslizar para o lado.',
    bestFor: ['Carrosséis educativos', 'Posts virais', 'Infográficos do Instagram'],
    compatibleModules: ['creative_director', 'copy_master', 'image_generator'],
    outputModes: ['single_prompt', 'carousel'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Square 1:1 or 4:5 portrait', 'Visual element subtly bleeding off right edge indicating continuation', 'Prominent headline spot'],
    promptAdditions: ['First slide cover for high-engagement Instagram carousel, 4:5 vertical, bold hook visual that leads viewer eye towards right edge.'],
    negativePromptAdditions: ['concluding image, dead-end composition'],
    tags: ['carrossel-capa', 'slide-1', 'gancho', 'arraste']
  },
  {
    code: '/feed-post',
    label: 'Aesthetic Feed Post 4:5',
    category: 'social_thumbnail',
    description: 'Postagem vertical 4:5 para feed do Instagram com máxima ocupação de tela.',
    bestFor: ['Posts de foto única', 'Lançamentos', 'Avisos de marca'],
    compatibleModules: ['creative_director', 'image_generator', 'virtual_tryon'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Vertical 4:5 ratio', 'Harmonious magazine-style composition', 'Balanced negative space and sophisticated typography'],
    promptAdditions: ['High-aesthetic Instagram 4:5 feed photography, balanced modern composition, rich tones, perfect negative space.'],
    negativePromptAdditions: ['harsh square crop, messy layout'],
    tags: ['feed', '4-5', 'instagram-feed', 'estetica']
  },
  {
    code: '/social-ad',
    label: 'Direct Response Social Ad',
    category: 'social_thumbnail',
    description: 'Anúncio visual para Meta Ads e TikTok Ads com foco em alta conversão.',
    bestFor: ['Tráfego pago', 'Campanhas de conversão', 'Criativos de venda'],
    compatibleModules: ['creative_director', 'copy_master', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Eye-stopping focal point', 'Problem vs solution visual cue', 'High contrast color accents'],
    promptAdditions: ['High-converting direct response social media ad creative, vibrant stopping-power visual, clear solution demonstration.'],
    negativePromptAdditions: ['vague artistic abstraction, no clear product or message'],
    tags: ['ad', 'meta-ads', 'conversao', 'trafego-pago']
  },
  {
    code: '/promo-banner',
    label: 'Promotional Sale Banner',
    category: 'social_thumbnail',
    description: 'Banner promocional com selo de oferta, desconto e urgência visual elegante.',
    bestFor: ['Black Friday', 'Saldão', 'Cupom de desconto', 'Datas sazonais'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Dynamic angled layout', 'Vibrant badge badge zone', 'Festive or high-urgency ambient glow'],
    promptAdditions: ['E-commerce promotional sale campaign banner, bold dynamic commercial aesthetic, designated zone for discount percentage badge.'],
    negativePromptAdditions: ['cheap discount flyer look, ugly low-res starbursts'],
    tags: ['promocao', 'black-friday', 'banner', 'desconto']
  },
  {
    code: '/launch-banner',
    label: 'New Product Launch Banner',
    category: 'social_thumbnail',
    description: 'Banner de lançamento de produto transmitindo novidade, inovação e exclusividade.',
    bestFor: ['Lançamentos oficiais', 'Coleções novas', 'Pré-vendas'],
    compatibleModules: ['creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Sleek pedestals or particle reveals', 'Dramatic spotlight from above', 'Prestigious high-tech or luxury mood'],
    promptAdditions: ['Official product launch reveal banner, dramatic top spotlight illuminating new product, futuristic particles, high exclusivity aura.'],
    negativePromptAdditions: ['dated retro look, boring plain background'],
    tags: ['lancamento', 'novo-produto', 'revelacao', 'exclusivo']
  },
  {
    code: '/hero-section',
    label: 'Website Hero Section 16:9',
    category: 'social_thumbnail',
    description: 'Header principal de landing page com produto à direita e espaço amplo para texto à esquerda.',
    bestFor: ['Landing pages', 'Header de e-commerce', 'Sites institucionais'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Widescreen 16:9 banner', 'Product or character positioned on right 40%', 'Clean gradient or minimalist backdrop on left 60%'],
    promptAdditions: ['Modern landing page hero banner illustration/photo, product positioned on right side with soft shadow, clean spacious background on left for H1 and CTA button.'],
    negativePromptAdditions: ['busy clutter across whole width, centered product blocking text'],
    tags: ['hero-section', 'landing-page', 'banner-site', 'widescreen']
  },
  {
    code: '/landing-cover',
    label: 'Lead Magnet & Course Cover',
    category: 'social_thumbnail',
    description: 'Capa 3D de ebook, curso ou treinamento digital com visual profissional e autoridade.',
    bestFor: ['Ebooks e PDFs', 'Cursos online', 'Infoprodutos'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['3D digital mockup perspective (tablet/book/box)', 'Professional dark or clean executive palette', 'High perceived value sheen'],
    promptAdditions: ['High perceived value digital product mockup cover, 3D box and tablet display, sleek executive aesthetic, premium gold or electric blue accents.'],
    negativePromptAdditions: ['flat 2D paper, blurry low quality graphics'],
    tags: ['infoproduto', 'ebook', 'curso', 'mockup-3d']
  },
  {
    code: '/attention-thumbnail',
    label: 'High-Attention Curiosity Hook',
    category: 'social_thumbnail',
    description: 'Visual magnético com elemento inesperado despertando curiosidade instantânea.',
    bestFor: ['Vídeos de mistério', 'Descobertas surpreendentes', 'Ganchos virais'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['High visual contrast anomaly', 'Shocked/curious expression', 'Arrow or glowing circle area of interest'],
    promptAdditions: ['Irresistible curiosity thumbnail hook, high visual tension, intriguing unexpected object under spotlight, vibrant mobile contrast.'],
    negativePromptAdditions: ['boring predictable photo, dull colors'],
    tags: ['curiosidade', 'magnetico', 'clique', 'viral']
  },
  {
    code: '/high-click-cover',
    label: 'High-Click Pattern Interrupt',
    category: 'social_thumbnail',
    description: 'Interrupção de padrão visual para quebrar a rolagem rápida do feed.',
    bestFor: ['TikTok e Reels', 'Anúncios de retenção', 'Shorts'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['thumbnail', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Unusual striking color combo (e.g. acid yellow & deep violet)', 'Sharp geometric framing', 'Dramatic scale juxtaposition'],
    promptAdditions: ['Pattern interrupt social media cover, bold striking color discordance, unexpected macro scale contrast, instant scroll-stopper.'],
    negativePromptAdditions: ['ordinary everyday photo, generic template'],
    tags: ['pattern-interrupt', 'scroll-stopper', 'alto-clique']
  },
  {
    code: '/text-led-cover',
    label: 'Text-Led Bold Statement Cover',
    category: 'social_thumbnail',
    description: 'Composição com espaço massivo para frase de impacto e tipografia imponente.',
    bestFor: ['Citações de impacto', 'Carrosséis conceituais', 'Manifestos de marca'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'carousel'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Clean textured minimalist background (paper/concrete/linen)', 'Huge central area reserved for bold typography', 'Subtle border accents'],
    promptAdditions: ['Editorial minimalist textured cover, tactile linen background with soft warm ambient lighting, vast empty center designed for oversized bold typography statement.'],
    negativePromptAdditions: ['cluttered textures, distracting photo in center'],
    tags: ['texto-forte', 'frase-impacto', 'minimalista', 'tipografia']
  },
  {
    code: '/bold-typography-cover',
    label: 'Heavy Editorial Typography Cover',
    category: 'social_thumbnail',
    description: 'Estética de revista com letras gigantes entrelaçadas atrás e à frente do sujeito.',
    bestFor: ['Capas de revista digital', 'Post de autoridade', 'Podcasts'],
    compatibleModules: ['creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Subject partially masking huge background letters', 'High-fashion portrait in center', 'Swiss/Brutalist typographic layout'],
    promptAdditions: ['Swiss graphic design magazine cover layout, subject layered naturally with massive bold display letterforms behind and in front, ultra-modern editorial chic.'],
    negativePromptAdditions: ['generic corporate design, unstyled plain text'],
    tags: ['letras-gigantes', 'revista', 'swiss-design', 'brutalismo']
  }
];
