import { PresetDefinition } from '../types';

export const TECHNICAL_PRESETS: PresetDefinition[] = [
  {
    code: '/3drender',
    label: 'Octane / Cinema 4D 3D Render',
    category: 'technical_3d',
    description: 'Render 3D fotorrealista com iluminação Octane, materiais PBR perfeitos e profundidade milimétrica.',
    bestFor: ['Design de produto', 'Embalagens 3D', 'Key visuals conceituais'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Octane render / Redshift aesthetic', 'Subsurface scattering on translucent materials', 'Raytraced reflections and caustics'],
    promptAdditions: ['Flawless 3D render in Octane/Cinema 4D style, photorealistic PBR shaders, subsurface scattering, crisp studio global illumination.'],
    negativePromptAdditions: ['low poly, jagged edges, untextured gray model, noisy GI'],
    tags: ['3d-render', 'octane', 'cinema-4d', 'pbr', 'fotorrealista']
  },
  {
    code: '/3dproduct',
    label: '3D Product Visualization on Podium',
    category: 'technical_3d',
    description: 'Visualização 3D de produto flutuando sobre pódio geométrico com partículas e luz suave.',
    bestFor: ['Lançamentos tech', 'Tênis e fones', 'Frascos cosméticos 3D'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Floating object with zero gravity tilt', 'Minimalist architectural pedestal (matte clay / stone)', 'Soft ambient occlusion contact shadows'],
    promptAdditions: ['3D industrial design product visualization, object hovering dynamically above minimalist geometric podium, soft ambient occlusion.'],
    negativePromptAdditions: ['flat 2D cut, harsh harsh raster lines'],
    tags: ['produto-3d', 'podio-3d', 'levitacao', 'design-industrial']
  },
  {
    code: '/isometric',
    label: 'Isometric 3D Cutaway Scene',
    category: 'technical_3d',
    description: 'Visão isométrica com ângulo de 30 graus mostrando cômodos em miniatura, fábricas ou micro-mundos.',
    bestFor: ['Infográficos 3D', 'Jogos isométricos', 'Arquitetura e processos'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['True orthographic isometric projection (30 degrees)', 'Cross-section miniature diorama', 'Charming miniature lighting'],
    promptAdditions: ['Detailed orthographic isometric 3D diorama render, vibrant miniature world cutaway, precise geometric perspective, studio lighting.'],
    negativePromptAdditions: ['perspective distortion, vanishing point convergence'],
    tags: ['isometrico', 'diorama', '30-graus', 'miniatura', 'ortografico']
  },
  {
    code: '/technicaldrawing',
    label: 'White-on-Black Technical Drawing',
    category: 'technical_3d',
    description: 'Desenho técnico com linhas brancas vetoriais precisas, cotas dimensionais e vista ortográfica.',
    bestFor: ['Patentes', 'Engenharia de produto', 'Estética industrial vintage'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Crisp white vector lines on solid matte black paper', 'Dimension callout arrows, annotations and part numbers', 'Orthogonal multi-view projection'],
    promptAdditions: ['Crisp white vector technical drafting drawing on matte black engineering paper, precise dimension lines, part callouts, schematic precision.'],
    negativePromptAdditions: ['messy colorful gradients, organic watercolor'],
    tags: ['desenho-tecnico', 'cotas', 'engenharia', 'patente', 'vetorial']
  },
  {
    code: '/blueprint',
    label: 'Classic Cyan Blueprint',
    category: 'technical_3d',
    description: 'Planta azul clássica (blueprint) de engenharia e arquitetura com grid milimétrico.',
    bestFor: ['Projetos arquitetônicos', 'Máquinas e motores', 'Visual científico'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Deep Prussian blue background with subtle white/cyan grid lines', 'Clean white architectural line drafting', 'Engineering stamps and title block'],
    promptAdditions: ['Authentic Prussian blue engineering blueprint, precise white vector drafting lines, subtle cyan grid, technical schematic annotations.'],
    negativePromptAdditions: ['photorealistic realistic textures, color photos'],
    tags: ['blueprint', 'planta-azul', 'engenharia', 'arquitetura', 'grid']
  },
  {
    code: '/blueprint3d',
    label: 'Holographic 3D Glowing Blueprint',
    category: 'technical_3d',
    description: 'Blueprint holográfico futurista brilhando no ar com linhas ciano e partículas de dados.',
    bestFor: ['Sci-fi tech', 'Interface de ficção científica (FUI)', 'Tony Stark lab style'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Glowing electric cyan holographic wireframe floating in dark space', 'Data telemetry numbers and orbital rings', 'Sci-fi UI HUD aesthetic'],
    promptAdditions: ['Glowing 3D holographic blueprint floating in dark high-tech lab, electric cyan wireframe vector paths, futuristic data telemetry overlay.'],
    negativePromptAdditions: ['paper drawing, daylight room'],
    tags: ['blueprint-3d', 'holograma', 'fui', 'hud', 'tony-stark']
  },
  {
    code: '/diagram',
    label: 'Clean Informational Diagram',
    category: 'technical_3d',
    description: 'Diagrama explicativo com setas de fluxo, legendas numéricas e estrutura passo a passo.',
    bestFor: ['Manuais de instrução', 'Infográficos educativos', 'Explicações de funcionamento'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Clean vector icons and flow arrows', 'Numbered steps 1-2-3', 'High contrast readability'],
    promptAdditions: ['Clean educational schematic diagram, clear sequential flow arrows, numbered process steps, high legibility instructional design.'],
    negativePromptAdditions: ['cluttered unreadable text, chaotic arrows'],
    tags: ['diagrama', 'infografico', 'passo-a-passo', 'explicativo']
  },
  {
    code: '/infographic',
    label: 'Visual Data Infographic Poster',
    category: 'technical_3d',
    description: 'Infográfico completo combinando ilustrações conceituais, gráficos de pizza/barra e estatísticas.',
    bestFor: ['Relatórios de dados', 'Posts educativos', 'Apresentações executivas'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Modular bento-box grid layout', 'Data visualizers, percentage charts and clean callouts', 'Harmonious infographic color palette'],
    promptAdditions: ['Comprehensive modern data infographic poster, modular bento grid layout, beautiful charts and metrics callouts, high visual hierarchy.'],
    negativePromptAdditions: ['confusing illegible numbers, chaotic alignment'],
    tags: ['infografico', 'dados', 'graficos', 'estatisticas', 'bento-grid']
  },
  {
    code: '/wireframe',
    label: '3D Polygonal Wireframe Mesh',
    category: 'technical_3d',
    description: 'Estrutura poligonal de malha 3D (wireframe) revelando a geometria e vértices do objeto.',
    bestFor: ['IA e computação gráfica', 'Design de software 3D', 'Visual futurista'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Glowing polygonal triangulated mesh', 'Visible vertices and wire edges', 'Dark background with luminous geometry'],
    promptAdditions: ['Luminous 3D polygonal wireframe mesh, glowing geometric vertices and edges defining vehicle/character topology, futuristic dark background.'],
    negativePromptAdditions: ['solid flat shading, plain 2D doodle'],
    tags: ['wireframe', 'malha-3d', 'poligonos', 'vertices', 'computacao-grafica']
  },
  {
    code: '/crosssection',
    label: 'Engineering Cross-Section Cut',
    category: 'technical_3d',
    description: 'Corte transversal mostrando as camadas internas de um motor, tênis, bateria ou relógio.',
    bestFor: ['Tecnologia de amortecimento', 'Engenharia de motores', 'Camadas de colchão e tecidos'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Precision slice revealing internal chambers and components', 'Material cross-hatching and layer differentiation', 'Exploded alignment'],
    promptAdditions: ['Industrial engineering cross-section cutaway, revealing complex internal mechanical layers, color-coded components, pristine studio lighting.'],
    negativePromptAdditions: ['solid exterior with no internal visibility, messy cut'],
    tags: ['corte-transversal', 'camadas-internas', 'cross-section', 'engenharia']
  },
  {
    code: '/cutaway',
    label: 'Architectural & Mechanical Cutaway',
    category: 'technical_3d',
    description: 'Visão em corte (estilo revista Veja/Superinteressante) mostrando o interior de edifícios, naves ou aviões.',
    bestFor: ['Infográficos de grande porte', 'Arquitetura', 'Veículos e aeronaves'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Cutaway exterior skin revealing interior rooms/cabins with active inhabitants', 'Meticulous micro-details in each section', 'Master editorial illustration'],
    promptAdditions: ['Masterclass architectural cutaway illustration, exterior wall peeled back to reveal multi-level interior rooms and activity, incredible micro-detail.'],
    negativePromptAdditions: ['blurry interior, empty featureless rooms'],
    tags: ['cutaway', 'corte-arquitetonico', 'superinteressante', 'interior']
  },
  {
    code: '/xray',
    label: 'X-Ray Transparent Tech View',
    category: 'technical_3d',
    description: 'Visualização transparente em raio-X com circuitos internos, chips e componentes brilhando por dentro.',
    bestFor: ['Fones TWS transparentes', 'Smartphones e chips', 'Hardware de ponta'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Translucent frosted casing', 'Glowing copper PCB traces, microchips and internal battery', 'High-tech translucent aesthetics'],
    promptAdditions: ['X-ray translucent product visualization, frosted transparent exterior revealing glowing internal microchip circuitry and copper traces, sleek tech vibe.'],
    negativePromptAdditions: ['solid opaque plastic, medical skeleton (unless requested)'],
    tags: ['raio-x', 'x-ray', 'transparente', 'circuitos', 'hardware']
  },
  {
    code: '/cad',
    label: 'CAD Engineering Solid Model',
    category: 'technical_3d',
    description: 'Modelo sólido de software CAD (SolidWorks/AutoCAD) com sombreamento metálico e linhas de tangência.',
    bestFor: ['Projetos de usinagem', 'Peças mecânicas', 'Peças automotivas'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Precision CAD solid model render', 'Accurate fillets, chamfers and screw threads', 'Clean neutral gradient CAD viewport'],
    promptAdditions: ['Parametric CAD solid model visualization, clean machined steel and aluminum surfaces, precise fillets and chamfers, engineering viewport rendering.'],
    negativePromptAdditions: ['organic blob, warped geometry'],
    tags: ['cad', 'solidworks', 'usinagem', 'peca-mecanica', 'precisao']
  }
];
