import { PresetDefinition } from '../types';

export const TYPOGRAPHY_PRESETS: PresetDefinition[] = [
  {
    code: '/bold-title',
    label: 'Bold Impactful Title Header',
    category: 'text_typography',
    description: 'Espaço e estilo para título em caixa alta, pesado e com forte peso visual no topo.',
    bestFor: ['Thumbnails', 'Pôsteres de ação', 'Headlines de impacto'],
    compatibleModules: ['creative_director', 'cinematic_engine', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Massive uppercase bold sans-serif display font area', 'High contrast against background', 'Tight letter-spacing (tracking)'],
    promptAdditions: ['Composition with dedicated top header area designed for massive bold uppercase condensed sans-serif title typography with extreme visual punch.'],
    negativePromptAdditions: ['unreadable script fonts, messy text overlapping subject face'],
    tags: ['bold-title', 'titulo-pesado', 'caixa-alta', 'impacto']
  },
  {
    code: '/clean-title',
    label: 'Clean Minimalist Title',
    category: 'text_typography',
    description: 'Tipografia minimalista com tracking expandido e elegância moderna.',
    bestFor: ['Moda de luxo', 'Arquitetura', 'Revistas de arte'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Light or regular geometric sans-serif', 'Generous letter spacing', 'Refined understated elegance'],
    promptAdditions: ['Minimalist layout with dedicated space for clean geometric title with wide tracking and understated modern luxury elegance.'],
    negativePromptAdditions: ['distressed grunge letters, cartoon fonts'],
    tags: ['clean-title', 'minimalista', 'espacado', 'elegante']
  },
  {
    code: '/red-accent-title',
    label: 'Red Accent Power Headline',
    category: 'text_typography',
    description: 'Título com destaque pontual em vermelho vibrante transmitindo perigo, urgência ou paixão.',
    bestFor: ['Thrillers', 'Notícias urgentes', 'Promoções e combate'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Selective crimson/scarlet red text highlight', 'Monochrome or dark background contrast', 'Visual heartbeat'],
    promptAdditions: ['Layout featuring high-contrast typography area with selective vivid crimson red accent keywords popping against dark backdrop.'],
    negativePromptAdditions: ['washed out pink text'],
    tags: ['vermelho', 'destaque-vermelho', 'urgencia', 'headline']
  },
  {
    code: '/cinematic-credits',
    label: 'Theatrical Billing Block & Movie Credits',
    category: 'text_typography',
    description: 'Área inferior clássica de créditos de cinema com fontes condensadas e logotipos de produtoras.',
    bestFor: ['Pôsteres de cinema oficiais', 'Key arts', 'Capas teatrais'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Bottom 15% dark clean gradient', 'Space for movie billing block typography and production company logos', 'Hollywood authentic finish'],
    promptAdditions: ['Authentic theatrical movie poster layout with clean dark lower margin formatted for billing block credit block text.'],
    negativePromptAdditions: ['messy chaotic scribble text across the whole image'],
    tags: ['creditos', 'billing-block', 'cinema-oficial', 'rodape']
  },
  {
    code: '/tagline-lock',
    label: 'Catchy Tagline / Slogan Lock',
    category: 'text_typography',
    description: 'Posicionamento estratégico para frase de efeito (slogan) logo acima ou abaixo do título principal.',
    bestFor: ['Slogans de filmes', 'Frases de marca', 'Ganchos conceituais'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Subtle secondary text zone', 'Smaller font size with wide tracking', 'Positioned harmoniously with main title'],
    promptAdditions: ['Poster composition incorporating dedicated space for an evocative single-line movie tagline above the main title lockup.'],
    negativePromptAdditions: ['long paragraph clutter'],
    tags: ['tagline', 'slogan', 'frase-efeito', 'subtitulo']
  },
  {
    code: '/release-date',
    label: 'Release Date / "NOS CINEMAS" Lock',
    category: 'text_typography',
    description: 'Destaque para data de lançamento, "EM BREVE" ou "DISPONÍVEL AGORA".',
    bestFor: ['Contagem regressiva', 'Divulgação de datas', 'Estreias'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Bold centered date placement at bottom or mid-lower third', 'Theatrical glow or clean box outline'],
    promptAdditions: ['Artwork featuring prominent clean space at bottom center for "COMING SOON" or theatrical release date text.'],
    negativePromptAdditions: ['unreadable numbers'],
    tags: ['data', 'estreia', 'brevemente', 'lancamento']
  },
  {
    code: '/coming-soon-lock',
    label: 'Coming Soon Teaser Badge',
    category: 'text_typography',
    description: 'Selo gráfico estilizado "Em Breve" com iluminação néon ou relevo metálico.',
    bestFor: ['Teasers', 'Pré-vendas', 'Coleções futuras'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Embossed metallic or glowing neon badge', 'Centered teaser lockup', 'High anticipation aura'],
    promptAdditions: ['Artistic layout with dedicated space for embossed metallic "COMING SOON" lockup with subtle cinematic lens glint.'],
    negativePromptAdditions: ['cheap sticker look'],
    tags: ['em-breve', 'teaser-badge', 'pre-venda']
  },
  {
    code: '/poster-typography',
    label: 'Full Theatrical Poster Typography Suite',
    category: 'text_typography',
    description: 'Hierarquia completa de pôster: Tagline no topo, Título gigante no centro e Créditos na base.',
    bestFor: ['Pôsteres completos', 'Key art de lançamento', 'Capas de festival'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Three-tier balanced hierarchy: top tagline, central hero title, bottom billing block', 'Professional theatrical proportion'],
    promptAdditions: ['Complete theatrical poster layout balance, spacious top for tagline, unobstructed middle for title, clean dark bottom for billing credits.'],
    negativePromptAdditions: ['unbalanced layout, text covering subject eyes'],
    tags: ['suite-tipografia', 'poster-completo', 'hierarquia', 'design-grafico']
  },
  {
    code: '/minimal-typography',
    label: 'Ultra-Minimal Swiss Typography',
    category: 'text_typography',
    description: 'Design gráfico estilo suíço com alinhamento em grid rigoroso e fontes modernistas.',
    bestFor: ['Arquitetura', 'Design de produto', 'Publicações independentes'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Strict Swiss grid alignment', 'Helvetica Neue or Akzidenz Grotesk aesthetic', 'Pure compositional balance'],
    promptAdditions: ['Swiss International Style graphic layout, strict asymmetrical grid alignment, ample negative space, understated modernist typography.'],
    negativePromptAdditions: ['grunge textures, chaotic misalignment'],
    tags: ['suico', 'swiss-style', 'helvetica', 'grid', 'minimalismo']
  },
  {
    code: '/high-contrast-title',
    label: 'High-Contrast Dual-Color Title',
    category: 'text_typography',
    description: 'Título com duas palavras contrastantes (ex: Branco e Amarelo Neon) para retenção imediata.',
    bestFor: ['Thumbnails de alta conversão', 'Criativos de anúncio', 'Títulos de curso'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Dual-tone text color split', 'High visual contrast', 'Extreme legibilidade em telas pequenas'],
    promptAdditions: ['High-contrast dual-color title design zone (bright white & vibrant neon yellow), optimized for instant legibility on mobile screens.'],
    negativePromptAdditions: ['low contrast gray text on dark'],
    tags: ['duas-cores', 'alto-contraste', 'amarelo-neon', 'mobile']
  },
  {
    code: '/dramatic-title',
    label: 'Chiseled 3D Metallic / Stone Title',
    category: 'text_typography',
    description: 'Espaço para título esculpido em metal escovado, ouro antigo ou pedra rúnica com iluminação 3D.',
    bestFor: ['Filmes de fantasia épica', 'Jogos RPG', 'Super-heróis'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['poster', 'single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['3D bevel and emboss metallic finish', 'Specular edge highlights along letterforms', 'Carved stone or forged steel texture'],
    promptAdditions: ['Composition accommodating a chiseled 3D metallic and stone title treatment with glowing edge specular highlights and forged texture.'],
    negativePromptAdditions: ['flat 2D cartoon text'],
    tags: ['3d-metal', 'pedra-esculpida', 'ouro-antigo', 'fantasia', 'rpg']
  },
  {
    code: '/center-title',
    label: 'Perfect Center-Weighted Title Lockup',
    category: 'text_typography',
    description: 'Composição com o sujeito dividido ou emoldurando um título central imponente.',
    bestFor: ['Capas de livro', 'Pôsteres conceituais', 'Música / Álbuns'],
    compatibleModules: ['cinematic_engine', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'poster'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Centered visual weight', 'Symmetrical framing embracing the central text block', 'Album cover aesthetic'],
    promptAdditions: ['Center-weighted symmetrical composition designed to showcase a bold centralized album or book title lockup in the middle focal plane.'],
    negativePromptAdditions: ['asymmetrical clutter'],
    tags: ['centro', 'capa-livro', 'album', 'simetria-central']
  },
  {
    code: '/lower-third-title',
    label: 'Clean Lower-Third Overlay Bar',
    category: 'text_typography',
    description: 'Barra de terço inferior limpa e transparente para identificação de nome, cargo ou produto.',
    bestFor: ['Entrevistas em vídeo', 'Depoimentos UGC', 'Apresentação de palestrantes'],
    compatibleModules: ['creative_director', 'image_generator'],
    outputModes: ['single_prompt'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Subtle translucent gradient bar on lower third', 'Clean white sans-serif name and sub-title', 'Broadcast television polish'],
    promptAdditions: ['Broadcast quality lower-third graphic zone, clean transparent gradient bar supporting two-line name and title text.'],
    negativePromptAdditions: ['giant opaque bar blocking subject chest'],
    tags: ['terco-inferior', 'lower-third', 'entrevista', 'nome-cargo']
  }
];
