import { PresetDefinition } from '../types';

export const UGC_PRESETS: PresetDefinition[] = [
  {
    code: '/ugc-natural',
    label: 'UGC Natural & Authentic',
    category: 'ugc_lifestyle',
    description: 'Estética espontânea de usuário real gravando no dia a dia sem parecer comercial.',
    bestFor: ['TikTok Ads', 'Reels orgânicos', 'Prova social autêntica'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator', 'copy_master'],
    outputModes: ['single_prompt', 'storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Natural smartphone camera perspective', 'Everyday room lighting', 'Relatable authentic expression and subtle handheld motion'],
    promptAdditions: ['Authentic UGC creator video frame, natural ambient smartphone camera look, real relatable person in everyday setting, zero artificial polish.'],
    negativePromptAdditions: ['overly polished glossy commercial, Hollywood lighting, fake stock photo smile'],
    tags: ['ugc', 'natural', 'autentico', 'criador', 'tiktok']
  },
  {
    code: '/ugc-selfie',
    label: 'UGC Front Camera Selfie',
    category: 'ugc_lifestyle',
    description: 'Ângulo de câmera frontal (selfie) com contato visual direto e intimista.',
    bestFor: ['Depoimentos', 'Reviews de skincare e maquiagem', 'Ganchos diretos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Front selfie camera framing at eye level', 'Direct engaged eye contact', 'Slight wide-angle smartphone perspective'],
    promptAdditions: ['POV front-facing selfie camera video frame of creator talking directly to viewer, expressive authentic emotion, relatable atmosphere.'],
    negativePromptAdditions: ['distant third-person shot, cold detached expression, artificial camera lens'],
    tags: ['selfie', 'camera-frontal', 'depoimento', 'contato-visual']
  },
  {
    code: '/ugc-speaking',
    label: 'UGC Speaking Head Review',
    category: 'ugc_lifestyle',
    description: 'Criador falando diretamente com a câmera enquanto demonstra o produto na mão.',
    bestFor: ['Reviews detalhados', 'Explicação de benefícios', 'Vídeos de recomendação'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'copy_master', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Bust/medium close-up framing', 'Product held up next to face', 'Natural conversational mouth movements'],
    promptAdditions: ['Creator speaking directly to audience holding product near face, energetic friendly vibe, modern home background with soft depth of field.'],
    negativePromptAdditions: ['lifeless mannequin face, product obscuring face awkwardly'],
    tags: ['review', 'falando', 'explicacao', 'criador']
  },
  {
    code: '/ugc-no-dialogue',
    label: 'UGC No-Dialogue & ASMR Sound',
    category: 'ugc_lifestyle',
    description: 'Vídeo focado 100% em ações visuais, texturas sonoras e legendas dinâmicas.',
    bestFor: ['TikTok sem fala', 'Shopee Video', 'Vídeos globais escaláveis'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Action-focused hands', 'Crisp tactile clicks and peels', 'Space for large center dynamic text overlay'],
    promptAdditions: ['Fast-paced no-dialogue UGC product demonstration, sensory tactile actions, crisp close-up focus, space for on-screen text hooks.'],
    negativePromptAdditions: ['talking head, static unmoving product, dark environment'],
    tags: ['sem-dialogo', 'asmr', 'texto-na-tela', 'global']
  },
  {
    code: '/lifestyle-demo',
    label: 'Lifestyle Daily Routine Demo',
    category: 'ugc_lifestyle',
    description: 'Integração perfeita do produto na rotina real de casa, treino ou trabalho.',
    bestFor: ['Garrafas térmicas', 'Roupas fitness', 'Utensílios de cozinha', 'Mochilas'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Natural morning or afternoon daylight', 'Dynamic environment (kitchen, gym, office)', 'Active functional usage'],
    promptAdditions: ['Lifestyle action shot of product seamlessly used in a realistic daily routine, warm natural window light, organic lifestyle aesthetics.'],
    negativePromptAdditions: ['isolated sterile studio, awkward forced posing'],
    tags: ['lifestyle', 'rotina', 'dia-a-dia', 'uso-real']
  },
  {
    code: '/day-in-the-life',
    label: 'Day In The Life (Vlog Style)',
    category: 'ugc_lifestyle',
    description: 'Estilo vlog acompanhando a jornada diária com o produto como facilitador.',
    bestFor: ['Vlogs de rotina', 'Produtos de bem-estar', 'Moda casual'],
    compatibleModules: ['creative_director', 'copy_master', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Over-the-shoulder and POV angles', 'Candid natural movements', 'Cozy lifestyle color grading'],
    promptAdditions: ['Vlog-style day-in-the-life candid snapshot, authentic aesthetic pacing, cozy organic colors, real ambient environment.'],
    negativePromptAdditions: ['stiff staged posture, formal corporate setting'],
    tags: ['vlog', 'rotina-diaria', 'estilo-de-vida']
  },
  {
    code: '/first-impression',
    label: 'First Impression & Unboxing Reaction',
    category: 'ugc_lifestyle',
    description: 'Reação genuína de surpresa e entusiasmo ao abrir e testar o produto pela primeira vez.',
    bestFor: ['Unboxings virais', 'Reações espontâneas', 'Lançamentos de novidades'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Expressive eyes and genuine smile', 'Hands peeling seal or opening package', 'Immediate tactile inspection'],
    promptAdditions: ['Genuine first impression reaction shot, creator happily surprised opening package, candid delight and close inspection.'],
    negativePromptAdditions: ['bored expression, fake exaggerated clowning, chaotic mess'],
    tags: ['primeira-impressao', 'unboxing', 'reacao', 'entusiasmo']
  },
  {
    code: '/casual-recommendation',
    label: 'Casual Friend Recommendation',
    category: 'ugc_lifestyle',
    description: 'Tom íntimo como se estivesse recomendando um segredo incrível para a melhor amiga.',
    bestFor: ['Dicas de beleza', 'Achadinhos de moda', 'Livros e cursos'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'copy_master', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Cozy intimate framing', 'Warm eye-level perspective', 'Gentle inviting smile'],
    promptAdditions: ['Casual friend-to-friend recommendation video frame, cozy living room warmth, authentic trustworthy body language.'],
    negativePromptAdditions: ['hard sales posture, corporate blazer, aggressive gestures'],
    tags: ['amiga', 'recomendacao', 'confianca', 'dica']
  },
  {
    code: '/native-ad',
    label: 'Native Social Feed Ad',
    category: 'ugc_lifestyle',
    description: 'Anúncio desenhado para se misturar 100% com o conteúdo orgânico do feed.',
    bestFor: ['TikTok Spark Ads', 'Instagram Reels Ads', 'Maior tempo de retenção'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'image_generator'],
    outputModes: ['single_prompt', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Zero commercial banners', 'Clean organic mobile look', 'High visual curiosity in first frame'],
    promptAdditions: ['Native social media feed creative, organic viral TikTok aesthetic, seamless non-ad appearance with maximum visual intrigue.'],
    negativePromptAdditions: ['cheesy ad banners, commercial watermark, salesy graphics'],
    tags: ['nativo', 'spark-ads', 'retencao', 'organico']
  },
  {
    code: '/creator-style',
    label: 'Creator Pro Aesthetic',
    category: 'ugc_lifestyle',
    description: 'Estética de influenciador com iluminação limpa e enquadramento equilibrado.',
    bestFor: ['Influenciadores digitais', 'Parcerias pagas', 'Conteúdo de autoridade'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'visual_reference', 'image_generator'],
    outputModes: ['single_prompt', 'storyboard'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Crisp 4K phone camera look', 'Clean background with warm accent lights', 'Polished yet relatable presence'],
    promptAdditions: ['High-level content creator setup, crisp 4K mobile cinematography, balanced ambient lighting, clean aesthetic room.'],
    negativePromptAdditions: ['grainy dark room, messy background, pixelated video'],
    tags: ['creator', 'influenciador', 'estetica', '4k']
  },
  {
    code: '/authentic-review',
    label: 'Authentic Honest Review',
    category: 'ugc_lifestyle',
    description: 'Formato de teste rigoroso e transparente destacando prós e pontos fortes reais.',
    bestFor: ['Eletrônicos', 'Ferramentas', 'Produtos com alta concorrência'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'copy_master', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Side-by-side test demonstration', 'Serious credible expression transitioning to satisfaction', 'Clear visual evidence'],
    promptAdditions: ['Honest transparent product review, creator conducting a clear stress-test on product, credible lighting, undeniable visual proof.'],
    negativePromptAdditions: ['unbelievable claims, cartoonish acting, blurry testing'],
    tags: ['review', 'teste', 'prova-real', 'credibilidade']
  },
  {
    code: '/soft-sell',
    label: 'Soft-Sell Storytelling',
    category: 'ugc_lifestyle',
    description: 'Venda sutil através de uma história envolvente onde o produto é o facilitador natural.',
    bestFor: ['Produtos de produtividade', 'Roupas confortáveis', 'Itens de bem-estar'],
    compatibleModules: ['creative_director', 'copy_master', 'image_generator'],
    outputModes: ['storyboard', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Story-driven cinematography', 'Warm natural tones', 'Subtle elegant product integration'],
    promptAdditions: ['Story-driven soft-sell lifestyle clip, gentle narrative cinematography, emotional relatability with seamless product presence.'],
    negativePromptAdditions: ['aggressive sales popups, flashing discounts, rushed feeling'],
    tags: ['soft-sell', 'storytelling', 'narrativa', 'emocional']
  },
  {
    code: '/social-proof-style',
    label: 'Social Proof & Community Love',
    category: 'ugc_lifestyle',
    description: 'Destaque para o fenômeno viral: "Todo mundo está usando isso na internet".',
    bestFor: ['Achadinhos virais', 'Tendências do momento', 'Urgência e FOMO'],
    compatibleModules: ['virtual_tryon', 'creative_director', 'copy_master', 'image_generator'],
    outputModes: ['single_prompt', 'campaign'],
    promptLanguage: 'en',
    uiLanguage: 'pt-BR',
    visualDNA: ['Dynamic energetic framing', 'Excited confident expression', 'Product shown in active social context'],
    promptAdditions: ['Viral social proof UGC snapshot, energetic creator demonstrating trending must-have product with high enthusiasm.'],
    negativePromptAdditions: ['depressed look, lonely dark scene, slow energy'],
    tags: ['prova-social', 'viral', 'tendencia', 'fomo']
  }
];
